import type { AdmiraltyCapabilityId } from "./capabilities";

export const configurationManagementClasses = [
  "RUNTIME_EDITABLE",
  "POLICY_EDITABLE",
  "FEATURE_FLAG_EDITABLE",
  "PROVIDER_SAFE_EDITABLE",
  "DEPLOYMENT_MANAGED",
  "SECRET_REFERENCE_ONLY",
  "IMMUTABLE_SECURITY",
  "EXTERNAL_OWNER",
  "OBSERVE_ONLY",
] as const;
export type ConfigurationManagementClass = (typeof configurationManagementClasses)[number];

export type AdmiraltyConfigurationDefinition = Readonly<{
  id: string;
  key: string;
  name: string;
  description: string;
  owner: string;
  managementClass: ConfigurationManagementClass;
  valueType: "BOOLEAN" | "INTEGER" | "DURATION_MS" | "REFERENCE" | "STATUS";
  sourceReference: string;
  allowedValues: string;
  validation: string;
  requiredCapability: AdmiraltyCapabilityId;
  reauthenticationRequired: boolean;
  supportGrantRequired: boolean;
  restartOrReload: string;
  previewBehavior: string;
  auditCategory: string;
  rollbackBehavior: string;
  secretClassification: "NONE" | "REFERENCE_ONLY";
  mutationCommandOwner: string | null;
}>;

/**
 * Source-bound classification of every setting currently projected by the
 * Chartroom. It intentionally omits unrelated environment variables and
 * treats secret/deployment values as references, never editable values.
 */
export const admiraltyConfigurationRegistry: readonly AdmiraltyConfigurationDefinition[] = [
  {
    id: "ADM-CFG-001",
    key: "platform.environment",
    name: "Runtime environment",
    description: "The deployment environment reported by this process.",
    owner: "Platform delivery",
    managementClass: "DEPLOYMENT_MANAGED",
    valueType: "STATUS",
    sourceReference: "NODE_ENV",
    allowedValues: "Deployment-selected environment label",
    validation: "Validated by the deployment host",
    requiredCapability: "CONFIG_OBSERVE",
    reauthenticationRequired: false,
    supportGrantRequired: false,
    restartOrReload: "Deployment restart",
    previewBehavior: "No in-product preview",
    auditCategory: "CONFIGURATION_READ",
    rollbackBehavior: "Deployment rollback",
    secretClassification: "NONE",
    mutationCommandOwner: null,
  },
  {
    id: "ADM-CFG-002",
    key: "platform.database-provider",
    name: "Database provider",
    description: "Safe provider identity only; connection material remains secret.",
    owner: "Platform delivery",
    managementClass: "SECRET_REFERENCE_ONLY",
    valueType: "REFERENCE",
    sourceReference: "DATABASE_URL",
    allowedValues: "Configured provider identity",
    validation: "Read-only safe projection",
    requiredCapability: "CONFIG_OBSERVE",
    reauthenticationRequired: false,
    supportGrantRequired: false,
    restartOrReload: "Deployment restart",
    previewBehavior: "No in-product preview",
    auditCategory: "SECRET_REFERENCE_READ",
    rollbackBehavior: "Deployment owner only",
    secretClassification: "REFERENCE_ONLY",
    mutationCommandOwner: null,
  },
  {
    id: "ADM-CFG-003",
    key: "wayfarer.oauth.google",
    name: "Google sign-in reference",
    description: "Configuration presence only; client identity and secrets are never shown.",
    owner: "Wayfarer",
    managementClass: "SECRET_REFERENCE_ONLY",
    valueType: "REFERENCE",
    sourceReference: "GOOGLE_CLIENT_ID",
    allowedValues: "Configured or not configured",
    validation: "Owner-projected presence",
    requiredCapability: "SECURITY_OBSERVE",
    reauthenticationRequired: false,
    supportGrantRequired: false,
    restartOrReload: "Owner deployment restart",
    previewBehavior: "No in-product preview",
    auditCategory: "SECRET_REFERENCE_READ",
    rollbackBehavior: "Wayfarer deployment owner only",
    secretClassification: "REFERENCE_ONLY",
    mutationCommandOwner: null,
  },
  {
    id: "ADM-CFG-004",
    key: "wayfarer.oauth.github",
    name: "GitHub sign-in reference",
    description: "Configuration presence only; client identity and secrets are never shown.",
    owner: "Wayfarer",
    managementClass: "SECRET_REFERENCE_ONLY",
    valueType: "REFERENCE",
    sourceReference: "GITHUB_CLIENT_ID",
    allowedValues: "Configured or not configured",
    validation: "Owner-projected presence",
    requiredCapability: "SECURITY_OBSERVE",
    reauthenticationRequired: false,
    supportGrantRequired: false,
    restartOrReload: "Owner deployment restart",
    previewBehavior: "No in-product preview",
    auditCategory: "SECRET_REFERENCE_READ",
    rollbackBehavior: "Wayfarer deployment owner only",
    secretClassification: "REFERENCE_ONLY",
    mutationCommandOwner: null,
  },
  {
    id: "ADM-CFG-005",
    key: "wayfarer.transactional-email",
    name: "Transactional email reference",
    description: "Provider presence and safe validation boundary only.",
    owner: "Wayfarer",
    managementClass: "SECRET_REFERENCE_ONLY",
    valueType: "REFERENCE",
    sourceReference: "EMAIL_PROVIDER",
    allowedValues: "Configured or not configured",
    validation: "Owner health contract when available",
    requiredCapability: "CONFIG_OBSERVE",
    reauthenticationRequired: false,
    supportGrantRequired: false,
    restartOrReload: "Owner deployment restart",
    previewBehavior: "No in-product preview",
    auditCategory: "SECRET_REFERENCE_READ",
    rollbackBehavior: "Wayfarer deployment owner only",
    secretClassification: "REFERENCE_ONLY",
    mutationCommandOwner: null,
  },
  {
    id: "ADM-CFG-006",
    key: "sealed-hold.storage",
    name: "Private storage reference",
    description: "Configured provider reference only; credentials and object paths are not exposed.",
    owner: "Sealed Hold",
    managementClass: "SECRET_REFERENCE_ONLY",
    valueType: "REFERENCE",
    sourceReference: "PRIVATE_CONTENT_STORAGE_PROVIDER",
    allowedValues: "Configured provider reference",
    validation: "Sealed Hold bounded health probe",
    requiredCapability: "CONTENT_OBSERVE",
    reauthenticationRequired: false,
    supportGrantRequired: false,
    restartOrReload: "Owner deployment restart",
    previewBehavior: "No in-product preview",
    auditCategory: "SECRET_REFERENCE_READ",
    rollbackBehavior: "Sealed Hold deployment owner only",
    secretClassification: "REFERENCE_ONLY",
    mutationCommandOwner: null,
  },
  {
    id: "ADM-CFG-007",
    key: "sealed-hold.scanner",
    name: "Private scanner reference",
    description: "Configured scanner reference only; scan credentials are not exposed.",
    owner: "Sealed Hold",
    managementClass: "SECRET_REFERENCE_ONLY",
    valueType: "REFERENCE",
    sourceReference: "PRIVATE_CONTENT_SCANNER_PROVIDER",
    allowedValues: "Configured provider reference",
    validation: "Sealed Hold bounded health probe",
    requiredCapability: "CONTENT_OBSERVE",
    reauthenticationRequired: false,
    supportGrantRequired: false,
    restartOrReload: "Owner deployment restart",
    previewBehavior: "No in-product preview",
    auditCategory: "SECRET_REFERENCE_READ",
    rollbackBehavior: "Sealed Hold deployment owner only",
    secretClassification: "REFERENCE_ONLY",
    mutationCommandOwner: null,
  },
  {
    id: "ADM-CFG-008",
    key: "sealed-hold.worker-enabled",
    name: "Private worker deployment state",
    description: "The Sealed Hold worker process is deployment-managed and remains non-editable here.",
    owner: "Sealed Hold",
    managementClass: "DEPLOYMENT_MANAGED",
    valueType: "STATUS",
    sourceReference: "PRIVATE_CONTENT_WORKER_ENABLED",
    allowedValues: "Deployment-selected state",
    validation: "Owner readiness probe",
    requiredCapability: "JOBS_OBSERVE",
    reauthenticationRequired: false,
    supportGrantRequired: false,
    restartOrReload: "Worker deployment restart",
    previewBehavior: "No in-product preview",
    auditCategory: "CONFIGURATION_READ",
    rollbackBehavior: "Sealed Hold deployment owner only",
    secretClassification: "NONE",
    mutationCommandOwner: null,
  },
  {
    id: "ADM-CFG-009",
    key: "harborlight.storage",
    name: "Community storage reference",
    description: "Configured provider reference only; storage credentials are never shown.",
    owner: "Harborlight",
    managementClass: "SECRET_REFERENCE_ONLY",
    valueType: "REFERENCE",
    sourceReference: "COMMUNITY_ASSET_STORAGE_PROVIDER",
    allowedValues: "Configured provider reference",
    validation: "Harborlight bounded health probe",
    requiredCapability: "CONTENT_OBSERVE",
    reauthenticationRequired: false,
    supportGrantRequired: false,
    restartOrReload: "Owner deployment restart",
    previewBehavior: "No in-product preview",
    auditCategory: "SECRET_REFERENCE_READ",
    rollbackBehavior: "Harborlight deployment owner only",
    secretClassification: "REFERENCE_ONLY",
    mutationCommandOwner: null,
  },
  {
    id: "ADM-CFG-010",
    key: "harborlight.scanner",
    name: "Community scanner reference",
    description: "Configured provider reference only; scanner credentials are never shown.",
    owner: "Harborlight",
    managementClass: "SECRET_REFERENCE_ONLY",
    valueType: "REFERENCE",
    sourceReference: "COMMUNITY_BINARY_SCANNER_PROVIDER",
    allowedValues: "Configured provider reference",
    validation: "Harborlight bounded health probe",
    requiredCapability: "CONTENT_OBSERVE",
    reauthenticationRequired: false,
    supportGrantRequired: false,
    restartOrReload: "Owner deployment restart",
    previewBehavior: "No in-product preview",
    auditCategory: "SECRET_REFERENCE_READ",
    rollbackBehavior: "Harborlight deployment owner only",
    secretClassification: "REFERENCE_ONLY",
    mutationCommandOwner: null,
  },
  {
    id: "ADM-CFG-011",
    key: "harborlight.worker-deployment",
    name: "Community worker deployment state",
    description: "Process enablement is deployment-managed; its runtime policy is separately governed below.",
    owner: "Harborlight",
    managementClass: "DEPLOYMENT_MANAGED",
    valueType: "STATUS",
    sourceReference: "COMMUNITY_WORKER_ENABLED",
    allowedValues: "Deployment-selected state",
    validation: "Worker runtime heartbeat when configured",
    requiredCapability: "JOBS_OBSERVE",
    reauthenticationRequired: false,
    supportGrantRequired: false,
    restartOrReload: "Worker deployment restart",
    previewBehavior: "No in-product preview",
    auditCategory: "CONFIGURATION_READ",
    rollbackBehavior: "Harborlight deployment owner only",
    secretClassification: "NONE",
    mutationCommandOwner: null,
  },
  {
    id: "ADM-CFG-012",
    key: "harborlight.rate-limit-provider",
    name: "Community rate-limit provider",
    description: "The rate-limit implementation is deployment-managed to preserve fail-closed request behavior.",
    owner: "Harborlight",
    managementClass: "DEPLOYMENT_MANAGED",
    valueType: "STATUS",
    sourceReference: "COMMUNITY_RATE_LIMIT_PROVIDER",
    allowedValues: "Deployment-selected provider",
    validation: "Fail-closed provider health behavior",
    requiredCapability: "CONFIG_OBSERVE",
    reauthenticationRequired: false,
    supportGrantRequired: false,
    restartOrReload: "Deployment restart",
    previewBehavior: "No in-product preview",
    auditCategory: "CONFIGURATION_READ",
    rollbackBehavior: "Harborlight deployment owner only",
    secretClassification: "NONE",
    mutationCommandOwner: null,
  },
  {
    id: "ADM-CFG-013",
    key: "harborlight.outbox.dispatch-enabled",
    name: "Accept new Community outbox work",
    description: "Whether Harborlight workers may claim new queued work. Expired-lease recovery remains enabled.",
    owner: "Harborlight",
    managementClass: "POLICY_EDITABLE",
    valueType: "BOOLEAN",
    sourceReference: "src/community/operational-policy.ts",
    allowedValues: "Enabled or paused",
    validation: "Boolean owner policy; revision-bound",
    requiredCapability: "CONFIG_OPERATE",
    reauthenticationRequired: true,
    supportGrantRequired: false,
    restartOrReload: "Effective on the next worker pass",
    previewBehavior: "Shows current and resulting policy",
    auditCategory: "GOVERNED_POLICY_CHANGE",
    rollbackBehavior: "Preview and apply the prior value with the new revision",
    secretClassification: "NONE",
    mutationCommandOwner: "Harborlight COMMUNITY_OUTBOX_RUNTIME_POLICY_UPDATE",
  },
  {
    id: "ADM-CFG-014",
    key: "harborlight.outbox.batch-size",
    name: "Community jobs per batch",
    description: "The bounded maximum number of queued Community jobs a worker pass may claim.",
    owner: "Harborlight",
    managementClass: "POLICY_EDITABLE",
    valueType: "INTEGER",
    sourceReference: "src/community/operational-policy.ts",
    allowedValues: "1 through 25",
    validation: "Bounded integer owner policy; revision-bound",
    requiredCapability: "CONFIG_OPERATE",
    reauthenticationRequired: true,
    supportGrantRequired: false,
    restartOrReload: "Effective on the next worker pass",
    previewBehavior: "Shows current and resulting policy",
    auditCategory: "GOVERNED_POLICY_CHANGE",
    rollbackBehavior: "Preview and apply the prior value with the new revision",
    secretClassification: "NONE",
    mutationCommandOwner: "Harborlight COMMUNITY_OUTBOX_RUNTIME_POLICY_UPDATE",
  },
  {
    id: "ADM-CFG-015",
    key: "harborlight.outbox.poll-interval",
    name: "Idle Community worker poll interval",
    description: "The bounded delay before an idle Harborlight worker checks the queue again.",
    owner: "Harborlight",
    managementClass: "POLICY_EDITABLE",
    valueType: "DURATION_MS",
    sourceReference: "src/community/operational-policy.ts",
    allowedValues: "1 second through 60 seconds",
    validation: "Bounded duration owner policy; revision-bound",
    requiredCapability: "CONFIG_OPERATE",
    reauthenticationRequired: true,
    supportGrantRequired: false,
    restartOrReload: "Effective for the next idle poll",
    previewBehavior: "Shows current and resulting policy",
    auditCategory: "GOVERNED_POLICY_CHANGE",
    rollbackBehavior: "Preview and apply the prior value with the new revision",
    secretClassification: "NONE",
    mutationCommandOwner: "Harborlight COMMUNITY_OUTBOX_RUNTIME_POLICY_UPDATE",
  },
];

export function configurationDefinition(key: string) {
  return admiraltyConfigurationRegistry.find((definition) => definition.key === key) ?? null;
}
