export type AdmiraltyErrorCode =
  | "ADMIRALTY_AUTH_REQUIRED"
  | "ADMIRALTY_CSRF_INVALID"
  | "ADMIRALTY_CAPABILITY_DENIED"
  | "ADMIRALTY_ASSURANCE_REQUIRED"
  | "ADMIRALTY_ASSURANCE_EXPIRED"
  | "ADMIRALTY_REAUTH_FAILED"
  | "SUPPORT_GRANT_REQUIRED"
  | "SUPPORT_GRANT_SCOPE_DENIED"
  | "SUPPORT_GRANT_EXPIRED"
  | "SUPPORT_GRANT_REVOKED"
  | "SUPPORT_CASE_INACTIVE"
  | "SUPPORT_CASE_ACTIVE_EXECUTION"
  | "SUPPORT_REPAIR_UNREGISTERED"
  | "SUPPORT_REPAIR_PROHIBITED"
  | "SUPPORT_REPAIR_CONSENT_DENIED"
  | "SUPPORT_REPAIR_RISK_DENIED"
  | "SUPPORT_REPAIR_CAPABILITY_DENIED"
  | "SUPPORT_REPAIR_ASSURANCE_REQUIRED"
  | "SUPPORT_REPAIR_HUMAN_APPROVAL_REQUIRED"
  | "SUPPORT_REPAIR_BUDGET_DENIED"
  | "SUPPORT_REPAIR_PRECONDITION_FAILED"
  | "SUPPORT_REPAIR_STALE"
  | "SUPPORT_REPAIR_CONFLICT"
  | "SUPPORT_REPAIR_AUDIT_REQUIRED"
  | "ADMIN_TARGET_NOT_FOUND"
  | "ADMIN_CONFLICT"
  | "ADMIN_AUDIT_UNAVAILABLE"
  | "ADMIN_OPERATION_UNAVAILABLE"
  | "ADMIN_VALIDATION_FAILED"
  | "ADMIN_IDEMPOTENCY_INVALID"
  | "ADMIN_REASON_INVALID"
  | "ADMIN_RATE_LIMITED";

export class AdmiraltyError extends Error {
  constructor(
    readonly code: AdmiraltyErrorCode,
    message: string,
    readonly status: number,
    readonly retryAfterSeconds?: number,
  ) {
    super(message);
    this.name = "AdmiraltyError";
  }
}

export function asAdmiraltyError(cause: unknown) {
  if (cause instanceof AdmiraltyError) return cause;
  return new AdmiraltyError("ADMIN_OPERATION_UNAVAILABLE", "The administrative operation is unavailable.", 503);
}
