import { describe, expect, it } from "vitest";
import { assertPublishingAllowed, assertTransition, communityItemTypes, manifestChecksum, normalizeHandle, releaseManifestSchema, sanitizeChronicleMetadata, toPublicListing } from "./domain";

describe("Harborlight domain foundation", () => {
  it("freezes capabilities for every typed item", () => expect(Object.keys(communityItemTypes)).toHaveLength(14));
  it("normalizes safe handles and rejects reserved or invisible names", () => { expect(normalizeHandle("Chart-Maker")).toBe("chart-maker"); expect(() => normalizeHandle("admin")).toThrow(); expect(() => normalizeHandle("chart\u200bmaker")).toThrow(); });
  it("enforces the publication matrix and server-side flag", () => { expect(() => assertTransition("DRAFT", "PUBLISHED")).toThrow(); expect(() => assertPublishingAllowed({ enabled: true, publicPublishingEnabled: false }, { role: "CREATOR" })).toThrow(); });
  it("creates deterministic immutable manifest checksums", () => { const manifest = releaseManifestSchema.parse({ schemaVersion: 1, listingId: "l", semanticVersion: "1.0.0", sourcePublishedTaleVersionId: "v", publicMetadata: { title: "Safe", spoilerLevel: "PREVIEW_SAFE" }, license: { key: "ALL_RIGHTS_RESERVED", version: 1 }, attribution: [{ displayName: "Creator", contributionType: "ORIGINAL_CREATOR" }] }); expect(manifestChecksum(manifest)).toBe(manifestChecksum(manifest)); });
  it("never projects secrets, private locations, or unpublished listings", () => { expect(toPublicListing({ slug: "safe", itemType: "CHRONICLE", title: "Safe", tags: [], spoilerLevel: "FINALE", visibility: "COMMUNITY", publicationStatus: "PUBLISHED", locationClass: "FICTIONAL", owner: { handle: "maker", displayName: "Maker", email: "secret@example.test" }, privateSnapshot: { answers: "secret", captainNotes: "secret" } })).toEqual(expect.not.objectContaining({ privateSnapshot: expect.anything() })); expect(toPublicListing({ slug: "home", itemType: "CHRONICLE", title: "Home", tags: [], spoilerLevel: "NONE", visibility: "COMMUNITY", publicationStatus: "PUBLISHED", locationClass: "PRIVATE_REAL_WORLD", owner: { handle: "maker", displayName: "Maker" } })).toBeNull(); });
  it("sanitizes Chronicle metadata by allowlist", () => expect(sanitizeChronicleMetadata({ title: "Safe", answers: "no", captainNotes: "no", exactCoordinates: "no" })).toEqual({ title: "Safe" }));
});
