-- Project Wayfarer Phase 1 MySQL production migration. Run only after backup and isolated rehearsal.
CREATE TABLE `UserAccount` (
  `id` VARCHAR(191) NOT NULL, `status` VARCHAR(191) NOT NULL DEFAULT 'PENDING_VERIFICATION',
  `legacyGameMasterId` VARCHAR(191) NULL, `claimedAt` DATETIME(3) NULL, `lastSeenAt` DATETIME(3) NULL,
  `lockedAt` DATETIME(3) NULL, `suspendedAt` DATETIME(3) NULL, `mergedIntoAccountId` VARCHAR(191) NULL,
  `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3), `updatedAt` DATETIME(3) NOT NULL,
  UNIQUE INDEX `UserAccount_legacyGameMasterId_key` (`legacyGameMasterId`),
  INDEX `UserAccount_status_lastSeenAt_idx` (`status`, `lastSeenAt`), PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
ALTER TABLE `UserAccount` ADD CONSTRAINT `UserAccount_legacyGameMasterId_fkey` FOREIGN KEY (`legacyGameMasterId`) REFERENCES `GameMasterUser`(`id`) ON DELETE SET NULL ON UPDATE CASCADE;
CREATE TABLE `AccountEmail` (`id` VARCHAR(191) NOT NULL, `accountId` VARCHAR(191) NOT NULL, `normalizedEmail` VARCHAR(191) NOT NULL, `displayEmail` VARCHAR(191) NOT NULL, `isPrimary` BOOLEAN NOT NULL DEFAULT true, `verificationState` VARCHAR(191) NOT NULL DEFAULT 'PENDING', `verifiedAt` DATETIME(3) NULL, `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3), `updatedAt` DATETIME(3) NOT NULL, UNIQUE INDEX `AccountEmail_normalizedEmail_key` (`normalizedEmail`), UNIQUE INDEX `AccountEmail_accountId_isPrimary_key` (`accountId`, `isPrimary`), INDEX `AccountEmail_accountId_verificationState_idx` (`accountId`, `verificationState`), PRIMARY KEY (`id`)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE TABLE `AccountCredential` (`id` VARCHAR(191) NOT NULL, `accountId` VARCHAR(191) NOT NULL, `passwordHash` VARCHAR(191) NOT NULL, `algorithm` VARCHAR(191) NOT NULL DEFAULT 'bcrypt', `changedAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3), `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3), UNIQUE INDEX `AccountCredential_accountId_key` (`accountId`), PRIMARY KEY (`id`)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE TABLE `AccountToken` (`id` VARCHAR(191) NOT NULL, `accountId` VARCHAR(191) NOT NULL, `purpose` VARCHAR(191) NOT NULL, `tokenHash` VARCHAR(191) NOT NULL, `expiresAt` DATETIME(3) NOT NULL, `consumedAt` DATETIME(3) NULL, `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3), UNIQUE INDEX `AccountToken_tokenHash_key` (`tokenHash`), INDEX `AccountToken_accountId_purpose_expiresAt_idx` (`accountId`, `purpose`, `expiresAt`), PRIMARY KEY (`id`)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE TABLE `AccountSession` (`id` VARCHAR(191) NOT NULL, `accountId` VARCHAR(191) NOT NULL, `tokenHash` VARCHAR(191) NOT NULL, `csrfToken` VARCHAR(191) NOT NULL, `deviceLabel` VARCHAR(191) NULL, `expiresAt` DATETIME(3) NOT NULL, `lastSeenAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3), `revokedAt` DATETIME(3) NULL, `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3), UNIQUE INDEX `AccountSession_tokenHash_key` (`tokenHash`), INDEX `AccountSession_accountId_expiresAt_idx` (`accountId`, `expiresAt`), PRIMARY KEY (`id`)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE TABLE `AccountRoleAssignment` (`id` VARCHAR(191) NOT NULL, `accountId` VARCHAR(191) NOT NULL, `role` VARCHAR(191) NOT NULL, `scopeType` VARCHAR(191) NOT NULL DEFAULT 'GLOBAL', `scopeId` VARCHAR(191) NULL, `grantedBy` VARCHAR(191) NULL, `grantedAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3), `revokedAt` DATETIME(3) NULL, UNIQUE INDEX `AccountRoleAssignment_accountId_role_scopeType_scopeId_key` (`accountId`, `role`, `scopeType`, `scopeId`), INDEX `AccountRoleAssignment_role_scopeType_scopeId_revokedAt_idx` (`role`, `scopeType`, `scopeId`, `revokedAt`), PRIMARY KEY (`id`)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE TABLE `SecurityEvent` (`id` VARCHAR(191) NOT NULL, `accountId` VARCHAR(191) NOT NULL, `eventType` VARCHAR(191) NOT NULL, `correlationId` VARCHAR(191) NULL, `metadata` LONGTEXT NOT NULL, `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3), INDEX `SecurityEvent_accountId_createdAt_idx` (`accountId`, `createdAt`), PRIMARY KEY (`id`)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE TABLE `WayfarerMigrationRecord` (`id` VARCHAR(191) NOT NULL, `sourceType` VARCHAR(191) NOT NULL, `sourceId` VARCHAR(191) NOT NULL, `accountId` VARCHAR(191) NULL, `status` VARCHAR(191) NOT NULL, `detail` LONGTEXT NOT NULL, `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3), `updatedAt` DATETIME(3) NOT NULL, UNIQUE INDEX `WayfarerMigrationRecord_sourceId_key` (`sourceId`), INDEX `WayfarerMigrationRecord_status_sourceType_idx` (`status`, `sourceType`), PRIMARY KEY (`id`)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
ALTER TABLE `PlayerProfile` ADD COLUMN `accountId` VARCHAR(191) NULL, ADD UNIQUE INDEX `PlayerProfile_accountId_key` (`accountId`);
ALTER TABLE `AccountEmail` ADD CONSTRAINT `AccountEmail_accountId_fkey` FOREIGN KEY (`accountId`) REFERENCES `UserAccount`(`id`) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE `AccountCredential` ADD CONSTRAINT `AccountCredential_accountId_fkey` FOREIGN KEY (`accountId`) REFERENCES `UserAccount`(`id`) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE `AccountToken` ADD CONSTRAINT `AccountToken_accountId_fkey` FOREIGN KEY (`accountId`) REFERENCES `UserAccount`(`id`) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE `AccountSession` ADD CONSTRAINT `AccountSession_accountId_fkey` FOREIGN KEY (`accountId`) REFERENCES `UserAccount`(`id`) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE `AccountRoleAssignment` ADD CONSTRAINT `AccountRoleAssignment_accountId_fkey` FOREIGN KEY (`accountId`) REFERENCES `UserAccount`(`id`) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE `SecurityEvent` ADD CONSTRAINT `SecurityEvent_accountId_fkey` FOREIGN KEY (`accountId`) REFERENCES `UserAccount`(`id`) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE `WayfarerMigrationRecord` ADD CONSTRAINT `WayfarerMigrationRecord_accountId_fkey` FOREIGN KEY (`accountId`) REFERENCES `UserAccount`(`id`) ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE `PlayerProfile` ADD CONSTRAINT `PlayerProfile_accountId_fkey` FOREIGN KEY (`accountId`) REFERENCES `UserAccount`(`id`) ON DELETE SET NULL ON UPDATE CASCADE;
-- The production runbook executes the deterministic player/Game Master backfill in bounded batches through scripts/wayfarer-migrate.ts.
