CREATE TABLE `TideglassCreatorAnnotation` (
    `id` VARCHAR(191) NOT NULL,
    `annotationKey` VARCHAR(191) NOT NULL,
    `revision` INTEGER NOT NULL,
    `chronicleId` VARCHAR(191) NOT NULL,
    `sourceEditionId` VARCHAR(191) NOT NULL,
    `sourceEditionChecksum` VARCHAR(191) NOT NULL,
    `targetEditionId` VARCHAR(191) NOT NULL,
    `targetEditionChecksum` VARCHAR(191) NOT NULL,
    `comparisonPolicyVersion` VARCHAR(191) NOT NULL,
    `scopeType` VARCHAR(191) NOT NULL,
    `category` VARCHAR(191) NULL,
    `changeRecordId` VARCHAR(191) NULL,
    `annotationKind` VARCHAR(191) NOT NULL,
    `headline` VARCHAR(191) NULL,
    `body` TEXT NULL,
    `spoilerLevel` VARCHAR(191) NOT NULL,
    `highlighted` BOOLEAN NOT NULL DEFAULT false,
    `replayGuidance` VARCHAR(191) NOT NULL DEFAULT 'NO_RECOMMENDATION',
    `createdByAccountId` VARCHAR(191) NOT NULL,
    `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `supersedesAnnotationId` VARCHAR(191) NULL,
    `state` VARCHAR(191) NOT NULL DEFAULT 'ACTIVE',
    `idempotencyKey` VARCHAR(191) NULL,
    UNIQUE INDEX `TideglassAnnotation_supersedes_key` (`supersedesAnnotationId`),
    UNIQUE INDEX `TideglassAnnotation_key_revision_key` (`annotationKey`, `revision`),
    UNIQUE INDEX `TideglassAnnotation_author_idempotency_key` (`createdByAccountId`, `idempotencyKey`),
    INDEX `TideglassAnnotation_pair_created_idx` (`chronicleId`, `sourceEditionId`, `targetEditionId`, `createdAt`),
    INDEX `TideglassAnnotation_change_record_idx` (`changeRecordId`),
    INDEX `TideglassAnnotation_author_created_idx` (`createdByAccountId`, `createdAt`),
    CONSTRAINT `TideglassAnnotation_revision_check` CHECK (`revision` > 0),
    CONSTRAINT `TideglassAnnotation_scope_check` CHECK ((`scopeType` = 'PAIR' AND `category` IS NULL AND `changeRecordId` IS NULL) OR (`scopeType` = 'CATEGORY' AND `category` IS NOT NULL AND `changeRecordId` IS NULL) OR (`scopeType` = 'CHANGE' AND `category` IS NULL AND `changeRecordId` IS NOT NULL)),
    CONSTRAINT `TideglassAnnotation_state_check` CHECK (`state` IN ('ACTIVE', 'WITHDRAWN')),
    CONSTRAINT `TideglassAnnotation_kind_check` CHECK (`annotationKind` IN ('HEADLINE', 'DETAIL', 'COMPATIBILITY', 'LIMITATION', 'REPLAY_GUIDANCE')),
    CONSTRAINT `TideglassAnnotation_spoiler_check` CHECK (`spoilerLevel` IN ('PREVIEW_SAFE', 'STORY_SPOILER', 'ENDING_SPOILER', 'CREATOR_ONLY', 'CAPTAIN_ONLY', 'PRIVATE_OR_REDACTED')),
    CONSTRAINT `TideglassAnnotation_replay_check` CHECK (`replayGuidance` IN ('NO_RECOMMENDATION', 'MINOR_UPDATE', 'WORTH_REVISITING', 'SUBSTANTIAL_NEW_CONTENT')),
    PRIMARY KEY (`id`),
    CONSTRAINT `TideglassAnnotation_chronicle_fkey` FOREIGN KEY (`chronicleId`) REFERENCES `Chronicle` (`id`) ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT `TideglassAnnotation_source_edition_fkey` FOREIGN KEY (`sourceEditionId`) REFERENCES `PublishedTaleVersion` (`id`) ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT `TideglassAnnotation_target_edition_fkey` FOREIGN KEY (`targetEditionId`) REFERENCES `PublishedTaleVersion` (`id`) ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT `TideglassAnnotation_author_fkey` FOREIGN KEY (`createdByAccountId`) REFERENCES `UserAccount` (`id`) ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT `TideglassAnnotation_supersedes_fkey` FOREIGN KEY (`supersedesAnnotationId`) REFERENCES `TideglassCreatorAnnotation` (`id`) ON DELETE RESTRICT ON UPDATE CASCADE
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
