-- Harborlight Phase 4 additive relational-integrity correction. Historical
-- moderation records are retained; only a report's optional current case can
-- detach when a parent case is intentionally removed by a governed repair.
ALTER TABLE `CommunityReport` ADD CONSTRAINT `CommunityReport_caseId_fkey` FOREIGN KEY (`caseId`) REFERENCES `CommunityModerationCase`(`id`) ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE `CommunityModerationCaseSubject` ADD CONSTRAINT `CommunityModerationCaseSubject_caseId_fkey` FOREIGN KEY (`caseId`) REFERENCES `CommunityModerationCase`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE `CommunityModerationCaseReport` ADD CONSTRAINT `CommunityModerationCaseReport_caseId_fkey` FOREIGN KEY (`caseId`) REFERENCES `CommunityModerationCase`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE, ADD CONSTRAINT `CommunityModerationCaseReport_reportId_fkey` FOREIGN KEY (`reportId`) REFERENCES `CommunityReport`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE `CommunityModerationCaseEvidence` ADD CONSTRAINT `CommunityModerationCaseEvidence_caseId_fkey` FOREIGN KEY (`caseId`) REFERENCES `CommunityModerationCase`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE `CommunityModerationCaseAssignment` ADD CONSTRAINT `CommunityModerationCaseAssignment_caseId_fkey` FOREIGN KEY (`caseId`) REFERENCES `CommunityModerationCase`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE `CommunityModerationCaseEvent` ADD CONSTRAINT `CommunityModerationCaseEvent_caseId_fkey` FOREIGN KEY (`caseId`) REFERENCES `CommunityModerationCase`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE `CommunityModerationAction` ADD CONSTRAINT `CommunityModerationAction_caseId_fkey` FOREIGN KEY (`caseId`) REFERENCES `CommunityModerationCase`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE `CommunitySanction` ADD CONSTRAINT `CommunitySanction_actionId_fkey` FOREIGN KEY (`actionId`) REFERENCES `CommunityModerationAction`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE `CommunityModerationAppeal` ADD CONSTRAINT `CommunityModerationAppeal_actionId_fkey` FOREIGN KEY (`actionId`) REFERENCES `CommunityModerationAction`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE, ADD CONSTRAINT `CommunityModerationAppeal_caseId_fkey` FOREIGN KEY (`caseId`) REFERENCES `CommunityModerationCase`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE `CommunityModerationAppealEvent` ADD CONSTRAINT `CommunityModerationAppealEvent_appealId_fkey` FOREIGN KEY (`appealId`) REFERENCES `CommunityModerationAppeal`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE `CommunityRestorationReceipt` ADD CONSTRAINT `CommunityRestorationReceipt_actionId_fkey` FOREIGN KEY (`actionId`) REFERENCES `CommunityModerationAction`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE, ADD CONSTRAINT `CommunityRestorationReceipt_caseId_fkey` FOREIGN KEY (`caseId`) REFERENCES `CommunityModerationCase`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE, ADD CONSTRAINT `CommunityRestorationReceipt_scanReceiptId_fkey` FOREIGN KEY (`scanReceiptId`) REFERENCES `CommunityScanReceipt`(`id`) ON DELETE SET NULL ON UPDATE CASCADE;
