-- Project Wayfarer Phase 1 MySQL production migration. Run only after backup and isolated rehearsal.
CREATE TABLE `UserAccount` (
  `id` VARCHAR(191) NOT NULL, `status` VARCHAR(191) NOT NULL DEFAULT 'PENDING_VERIFICATION',
  `legacyGameMasterId` VARCHAR(191) NULL, `claimedAt` DATETIME(3) NULL, `lastSeenAt` DATETIME(3) NULL,
  `lockedAt` DATETIME(3) NULL, `suspendedAt` DATETIME(3) NULL, `mergedIntoAccountId` VARCHAR(191) NULL,
  `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3), `updatedAt` DATETIME(3) NOT NULL,
  UNIQUE INDEX `UserAccount_legacyGameMasterId_key` (`legacyGameMasterId`),
  INDEX `UserAccount_status_lastSeenAt_idx` (`status`, `lastSeenAt`), PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
ALTER TABLE `UserAccount` ADD CONSTRAINT `UserAccount_legacyGameMasterId_fkey` FOREIGN KEY (`legacyGameMasterId`) REFERENCES `GameMasterUser`(`id`) ON DELETE SET NULL ON UPDATE CASCADE;
CREATE TABLE `AccountEmail` (`id` VARCHAR(191) NOT NULL, `accountId` VARCHAR(191) NOT NULL, `normalizedEmail` VARCHAR(191) NOT NULL, `displayEmail` VARCHAR(191) NOT NULL, `isPrimary` BOOLEAN NOT NULL DEFAULT true, `verificationState` VARCHAR(191) NOT NULL DEFAULT 'PENDING', `verifiedAt` DATETIME(3) NULL, `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3), `updatedAt` DATETIME(3) NOT NULL, UNIQUE INDEX `AccountEmail_normalizedEmail_key` (`normalizedEmail`), UNIQUE INDEX `AccountEmail_accountId_isPrimary_key` (`accountId`, `isPrimary`), INDEX `AccountEmail_accountId_verificationState_idx` (`accountId`, `verificationState`), PRIMARY KEY (`id`)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE TABLE `AccountCredential` (`id` VARCHAR(191) NOT NULL, `accountId` VARCHAR(191) NOT NULL, `passwordHash` VARCHAR(191) NOT NULL, `algorithm` VARCHAR(191) NOT NULL DEFAULT 'bcrypt', `changedAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3), `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3), UNIQUE INDEX `AccountCredential_accountId_key` (`accountId`), PRIMARY KEY (`id`)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE TABLE `AccountToken` (`id` VARCHAR(191) NOT NULL, `accountId` VARCHAR(191) NOT NULL, `purpose` VARCHAR(191) NOT NULL, `tokenHash` VARCHAR(191) NOT NULL, `expiresAt` DATETIME(3) NOT NULL, `consumedAt` DATETIME(3) NULL, `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3), UNIQUE INDEX `AccountToken_tokenHash_key` (`tokenHash`), INDEX `AccountToken_accountId_purpose_expiresAt_idx` (`accountId`, `purpose`, `expiresAt`), PRIMARY KEY (`id`)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE TABLE `AccountSession` (`id` VARCHAR(191) NOT NULL, `accountId` VARCHAR(191) NOT NULL, `tokenHash` VARCHAR(191) NOT NULL, `csrfToken` VARCHAR(191) NOT NULL, `deviceLabel` VARCHAR(191) NULL, `expiresAt` DATETIME(3) NOT NULL, `lastSeenAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3), `revokedAt` DATETIME(3) NULL, `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3), UNIQUE INDEX `AccountSession_tokenHash_key` (`tokenHash`), INDEX `AccountSession_accountId_expiresAt_idx` (`accountId`, `expiresAt`), PRIMARY KEY (`id`)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE TABLE `AccountRoleAssignment` (`id` VARCHAR(191) NOT NULL, `accountId` VARCHAR(191) NOT NULL, `role` VARCHAR(191) NOT NULL, `scopeType` VARCHAR(191) NOT NULL DEFAULT 'GLOBAL', `scopeId` VARCHAR(191) NULL, `grantedBy` VARCHAR(191) NULL, `grantedAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3), `revokedAt` DATETIME(3) NULL, UNIQUE INDEX `AccountRoleAssignment_accountId_role_scopeType_scopeId_key` (`accountId`, `role`, `scopeType`, `scopeId`), INDEX `AccountRoleAssignment_role_scopeType_scopeId_revokedAt_idx` (`role`, `scopeType`, `scopeId`, `revokedAt`), PRIMARY KEY (`id`)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE TABLE `SecurityEvent` (`id` VARCHAR(191) NOT NULL, `accountId` VARCHAR(191) NOT NULL, `eventType` VARCHAR(191) NOT NULL, `correlationId` VARCHAR(191) NULL, `metadata` LONGTEXT NOT NULL, `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3), INDEX `SecurityEvent_accountId_createdAt_idx` (`accountId`, `createdAt`), PRIMARY KEY (`id`)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE TABLE `WayfarerMigrationRecord` (`id` VARCHAR(191) NOT NULL, `sourceType` VARCHAR(191) NOT NULL, `sourceId` VARCHAR(191) NOT NULL, `accountId` VARCHAR(191) NULL, `status` VARCHAR(191) NOT NULL, `detail` LONGTEXT NOT NULL, `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3), `updatedAt` DATETIME(3) NOT NULL, UNIQUE INDEX `WayfarerMigrationRecord_sourceId_key` (`sourceId`), INDEX `WayfarerMigrationRecord_status_sourceType_idx` (`status`, `sourceType`), PRIMARY KEY (`id`)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
ALTER TABLE `PlayerProfile` ADD COLUMN `accountId` VARCHAR(191) NULL, ADD UNIQUE INDEX `PlayerProfile_accountId_key` (`accountId`);
ALTER TABLE `AccountEmail` ADD CONSTRAINT `AccountEmail_accountId_fkey` FOREIGN KEY (`accountId`) REFERENCES `UserAccount`(`id`) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE `AccountCredential` ADD CONSTRAINT `AccountCredential_accountId_fkey` FOREIGN KEY (`accountId`) REFERENCES `UserAccount`(`id`) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE `AccountToken` ADD CONSTRAINT `AccountToken_accountId_fkey` FOREIGN KEY (`accountId`) REFERENCES `UserAccount`(`id`) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE `AccountSession` ADD CONSTRAINT `AccountSession_accountId_fkey` FOREIGN KEY (`accountId`) REFERENCES `UserAccount`(`id`) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE `AccountRoleAssignment` ADD CONSTRAINT `AccountRoleAssignment_accountId_fkey` FOREIGN KEY (`accountId`) REFERENCES `UserAccount`(`id`) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE `SecurityEvent` ADD CONSTRAINT `SecurityEvent_accountId_fkey` FOREIGN KEY (`accountId`) REFERENCES `UserAccount`(`id`) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE `WayfarerMigrationRecord` ADD CONSTRAINT `WayfarerMigrationRecord_accountId_fkey` FOREIGN KEY (`accountId`) REFERENCES `UserAccount`(`id`) ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE `PlayerProfile` ADD CONSTRAINT `PlayerProfile_accountId_fkey` FOREIGN KEY (`accountId`) REFERENCES `UserAccount`(`id`) ON DELETE SET NULL ON UPDATE CASCADE;
-- These nullable actor relations are part of the same additive Wayfarer
-- identity contract as PlayerProfile.accountId. They retain historical string
-- snapshots while ensuring every new Chronicle write can be account-rooted.
ALTER TABLE `Chronicle` ADD COLUMN `creatorAccountId` VARCHAR(191) NULL, ADD INDEX `Chronicle_creatorAccountId_updatedAt_idx` (`creatorAccountId`, `updatedAt`);
ALTER TABLE `TaleDraft` ADD COLUMN `createdByAccountId` VARCHAR(191) NULL, ADD INDEX `TaleDraft_createdByAccountId_idx` (`createdByAccountId`);
ALTER TABLE `PublishedTaleVersion` ADD COLUMN `publishedByAccountId` VARCHAR(191) NULL, ADD INDEX `PublishedTaleVersion_publishedByAccountId_idx` (`publishedByAccountId`);
ALTER TABLE `TaleAsset` ADD COLUMN `createdByAccountId` VARCHAR(191) NULL, ADD INDEX `TaleAsset_createdByAccountId_idx` (`createdByAccountId`);
ALTER TABLE `TaleSession` ADD COLUMN `captainAccountId` VARCHAR(191) NULL, ADD INDEX `TaleSession_captainAccountId_status_idx` (`captainAccountId`, `status`);
ALTER TABLE `Invitation` ADD COLUMN `creatorAccountId` VARCHAR(191) NULL, ADD INDEX `Invitation_creatorAccountId_status_idx` (`creatorAccountId`, `status`);
ALTER TABLE `InvitationEvent` ADD COLUMN `actorAccountId` VARCHAR(191) NULL, ADD INDEX `InvitationEvent_actorAccountId_createdAt_idx` (`actorAccountId`, `createdAt`);
ALTER TABLE `RevealState` ADD COLUMN `revealedByAccountId` VARCHAR(191) NULL, ADD INDEX `RevealState_revealedByAccountId_revealedAt_idx` (`revealedByAccountId`, `revealedAt`);
ALTER TABLE `PlatformAuditEvent` ADD COLUMN `actorAccountId` VARCHAR(191) NULL, ADD INDEX `PlatformAuditEvent_actorAccountId_createdAt_idx` (`actorAccountId`, `createdAt`);
ALTER TABLE `Chronicle` ADD CONSTRAINT `Chronicle_creatorAccountId_fkey` FOREIGN KEY (`creatorAccountId`) REFERENCES `UserAccount`(`id`) ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE `TaleDraft` ADD CONSTRAINT `TaleDraft_createdByAccountId_fkey` FOREIGN KEY (`createdByAccountId`) REFERENCES `UserAccount`(`id`) ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE `PublishedTaleVersion` ADD CONSTRAINT `PublishedTaleVersion_publishedByAccountId_fkey` FOREIGN KEY (`publishedByAccountId`) REFERENCES `UserAccount`(`id`) ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE `TaleAsset` ADD CONSTRAINT `TaleAsset_createdByAccountId_fkey` FOREIGN KEY (`createdByAccountId`) REFERENCES `UserAccount`(`id`) ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE `TaleSession` ADD CONSTRAINT `TaleSession_captainAccountId_fkey` FOREIGN KEY (`captainAccountId`) REFERENCES `UserAccount`(`id`) ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE `Invitation` ADD CONSTRAINT `Invitation_creatorAccountId_fkey` FOREIGN KEY (`creatorAccountId`) REFERENCES `UserAccount`(`id`) ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE `InvitationEvent` ADD CONSTRAINT `InvitationEvent_actorAccountId_fkey` FOREIGN KEY (`actorAccountId`) REFERENCES `UserAccount`(`id`) ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE `RevealState` ADD CONSTRAINT `RevealState_revealedByAccountId_fkey` FOREIGN KEY (`revealedByAccountId`) REFERENCES `UserAccount`(`id`) ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE `PlatformAuditEvent` ADD CONSTRAINT `PlatformAuditEvent_actorAccountId_fkey` FOREIGN KEY (`actorAccountId`) REFERENCES `UserAccount`(`id`) ON DELETE SET NULL ON UPDATE CASCADE;
-- The production runbook executes the deterministic player/Game Master backfill in bounded batches through scripts/wayfarer-migrate.ts.
