CREATE TABLE `PrivilegedAssurance` (
    `id` VARCHAR(191) NOT NULL,
    `accountId` VARCHAR(191) NOT NULL,
    `accountSessionId` VARCHAR(191) NOT NULL,
    `assuranceLevel` VARCHAR(191) NOT NULL DEFAULT 'ADMIN_REAUTHENTICATED',
    `method` VARCHAR(191) NOT NULL,
    `issuedAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `expiresAt` DATETIME(3) NOT NULL,
    `revokedAt` DATETIME(3) NULL,
    `correlationId` VARCHAR(191) NOT NULL,
    INDEX `PrivilegedAssurance_account_session_expiry_revocation_idx` (`accountId`, `accountSessionId`, `expiresAt`, `revokedAt`),
    INDEX `PrivilegedAssurance_correlationId_idx` (`correlationId`),
    PRIMARY KEY (`id`),
    CONSTRAINT `PrivilegedAssurance_accountId_fkey` FOREIGN KEY (`accountId`) REFERENCES `UserAccount` (`id`) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT `PrivilegedAssurance_accountSessionId_fkey` FOREIGN KEY (`accountSessionId`) REFERENCES `AccountSession` (`id`) ON DELETE CASCADE ON UPDATE CASCADE
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE `SupportAccessRequest` (
    `id` VARCHAR(191) NOT NULL,
    `requestingAdminAccountId` VARCHAR(191) NOT NULL,
    `targetAccountId` VARCHAR(191) NOT NULL,
    `purpose` VARCHAR(191) NOT NULL,
    `requestedScopes` LONGTEXT NOT NULL,
    `status` VARCHAR(191) NOT NULL DEFAULT 'REQUESTED',
    `requestedAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `expiresAt` DATETIME(3) NOT NULL,
    `decisionAt` DATETIME(3) NULL,
    `decisionByTargetAccountId` VARCHAR(191) NULL,
    `cancelledAt` DATETIME(3) NULL,
    `correlationId` VARCHAR(191) NOT NULL,
    `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `updatedAt` DATETIME(3) NOT NULL,
    UNIQUE INDEX `SupportAccessRequest_correlationId_key` (`correlationId`),
    INDEX `SupportAccessRequest_target_status_expiry_idx` (`targetAccountId`, `status`, `expiresAt`),
    INDEX `SupportAccessRequest_operator_status_expiry_idx` (`requestingAdminAccountId`, `status`, `expiresAt`),
    PRIMARY KEY (`id`),
    CONSTRAINT `SupportAccessRequest_operator_fkey` FOREIGN KEY (`requestingAdminAccountId`) REFERENCES `UserAccount` (`id`) ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT `SupportAccessRequest_target_fkey` FOREIGN KEY (`targetAccountId`) REFERENCES `UserAccount` (`id`) ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT `SupportAccessRequest_decision_fkey` FOREIGN KEY (`decisionByTargetAccountId`) REFERENCES `UserAccount` (`id`) ON DELETE SET NULL ON UPDATE CASCADE
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE `SupportAccessGrant` (
    `id` VARCHAR(191) NOT NULL,
    `requestId` VARCHAR(191) NOT NULL,
    `operatorAccountId` VARCHAR(191) NOT NULL,
    `targetAccountId` VARCHAR(191) NOT NULL,
    `grantedScopes` LONGTEXT NOT NULL,
    `status` VARCHAR(191) NOT NULL DEFAULT 'ACTIVE',
    `issuedAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `expiresAt` DATETIME(3) NOT NULL,
    `revokedAt` DATETIME(3) NULL,
    `revokedByAccountId` VARCHAR(191) NULL,
    `revocationReason` VARCHAR(191) NULL,
    `correlationId` VARCHAR(191) NOT NULL,
    UNIQUE INDEX `SupportAccessGrant_requestId_key` (`requestId`),
    INDEX `SupportAccessGrant_operator_status_expiry_idx` (`operatorAccountId`, `status`, `expiresAt`),
    INDEX `SupportAccessGrant_target_status_expiry_idx` (`targetAccountId`, `status`, `expiresAt`),
    INDEX `SupportAccessGrant_correlationId_idx` (`correlationId`),
    PRIMARY KEY (`id`),
    CONSTRAINT `SupportAccessGrant_requestId_fkey` FOREIGN KEY (`requestId`) REFERENCES `SupportAccessRequest` (`id`) ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT `SupportAccessGrant_operator_fkey` FOREIGN KEY (`operatorAccountId`) REFERENCES `UserAccount` (`id`) ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT `SupportAccessGrant_target_fkey` FOREIGN KEY (`targetAccountId`) REFERENCES `UserAccount` (`id`) ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT `SupportAccessGrant_revoker_fkey` FOREIGN KEY (`revokedByAccountId`) REFERENCES `UserAccount` (`id`) ON DELETE SET NULL ON UPDATE CASCADE
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
