ALTER TABLE `VisionWaypointVersion`
  ADD COLUMN `authoringRevision` INTEGER NOT NULL DEFAULT 1,
  ADD COLUMN `authoringMode` VARCHAR(191) NOT NULL DEFAULT 'GUIDED',
  ADD COLUMN `currentWizardStep` INTEGER NOT NULL DEFAULT 1;

ALTER TABLE `VisionRecordingAsset`
  ADD COLUMN `creatorNotes` TEXT NULL,
  ADD COLUMN `role` VARCHAR(191) NOT NULL DEFAULT 'UNASSIGNED',
  ADD COLUMN `isUsable` BOOLEAN NOT NULL DEFAULT true,
  ADD COLUMN `segmentStartMs` INTEGER NULL,
  ADD COLUMN `segmentEndMs` INTEGER NULL,
  ADD COLUMN `sourceAssetId` VARCHAR(191) NULL,
  ADD COLUMN `integrityState` VARCHAR(191) NOT NULL DEFAULT 'LOCAL_VERIFIED',
  ADD COLUMN `cloudState` VARCHAR(191) NOT NULL DEFAULT 'LOCAL_ONLY';

ALTER TABLE `VisionBuildJob`
  ADD COLUMN `inputSchemaVersion` INTEGER NOT NULL DEFAULT 1,
  ADD COLUMN `buildInput` LONGTEXT NOT NULL,
  ADD COLUMN `inputHash` VARCHAR(191) NULL;

ALTER TABLE `VisionWaypointTestRun`
  ADD COLUMN `name` VARCHAR(191) NOT NULL DEFAULT 'Untitled test',
  ADD COLUMN `instructions` TEXT NOT NULL,
  ADD COLUMN `environment` LONGTEXT NOT NULL,
  ADD COLUMN `assetRole` VARCHAR(191) NOT NULL DEFAULT 'VALIDATION',
  ADD COLUMN `lockedAt` DATETIME(3) NULL;
