-- Harborlight Phase 4 additive MySQL migration. Application transitions enforce
-- policy; tables retain durable, auditable case and operational state.
ALTER TABLE `CommunityReport` ADD COLUMN `caseId` VARCHAR(191) NULL, ADD COLUMN `idempotencyKey` VARCHAR(191) NULL;
CREATE UNIQUE INDEX `CommunityReport_idempotencyKey_key` ON `CommunityReport` (`idempotencyKey`);
CREATE INDEX `CommunityReport_caseId_createdAt_idx` ON `CommunityReport` (`caseId`, `createdAt`);

CREATE TABLE `CommunityModerationCase` (`id` VARCHAR(191) NOT NULL, `caseKey` VARCHAR(191) NOT NULL, `status` VARCHAR(64) NOT NULL DEFAULT 'OPEN', `severity` VARCHAR(64) NOT NULL DEFAULT 'MEDIUM', `priority` VARCHAR(64) NOT NULL DEFAULT 'MEDIUM', `primaryReasonCode` VARCHAR(191) NOT NULL, `subjectFingerprint` VARCHAR(191) NOT NULL, `revision` INT NOT NULL DEFAULT 1, `assignedAccountId` VARCHAR(191) NULL, `conflictAccountId` VARCHAR(191) NULL, `correlationId` VARCHAR(191) NOT NULL, `openedAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3), `closedAt` DATETIME(3) NULL, `updatedAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3), PRIMARY KEY (`id`), UNIQUE KEY `CommunityModerationCase_caseKey_key` (`caseKey`), KEY `CommunityModerationCase_status_priority_openedAt_idx` (`status`, `priority`, `openedAt`), KEY `CommunityModerationCase_subjectFingerprint_status_idx` (`subjectFingerprint`, `status`), KEY `CommunityModerationCase_assignedAccountId_status_idx` (`assignedAccountId`, `status`)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE TABLE `CommunityModerationCaseSubject` (`id` VARCHAR(191) NOT NULL, `caseId` VARCHAR(191) NOT NULL, `subjectType` VARCHAR(64) NOT NULL, `subjectId` VARCHAR(191) NOT NULL, `subjectChecksum` VARCHAR(191) NULL, `tombstone` LONGTEXT NOT NULL, `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3), PRIMARY KEY (`id`), UNIQUE KEY `CommunityModerationCaseSubject_caseId_subjectType_subjectId_key` (`caseId`, `subjectType`, `subjectId`), KEY `CommunityModerationCaseSubject_subjectType_subjectId_idx` (`subjectType`, `subjectId`)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE TABLE `CommunityModerationCaseReport` (`id` VARCHAR(191) NOT NULL, `caseId` VARCHAR(191) NOT NULL, `reportId` VARCHAR(191) NOT NULL, `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3), PRIMARY KEY (`id`), UNIQUE KEY `CommunityModerationCaseReport_reportId_key` (`reportId`), KEY `CommunityModerationCaseReport_caseId_createdAt_idx` (`caseId`, `createdAt`)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE TABLE `CommunityModerationCaseEvidence` (`id` VARCHAR(191) NOT NULL, `caseId` VARCHAR(191) NOT NULL, `kind` VARCHAR(64) NOT NULL, `checksum` CHAR(64) NOT NULL, `schemaVersion` INT NOT NULL DEFAULT 1, `safeSnapshot` LONGTEXT NOT NULL, `accessClass` VARCHAR(64) NOT NULL DEFAULT 'MODERATOR', `createdBy` VARCHAR(191) NOT NULL, `correlationId` VARCHAR(191) NOT NULL, `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3), PRIMARY KEY (`id`), UNIQUE KEY `CommunityModerationCaseEvidence_caseId_kind_checksum_key` (`caseId`, `kind`, `checksum`), KEY `CommunityModerationCaseEvidence_caseId_createdAt_idx` (`caseId`, `createdAt`)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE TABLE `CommunityModerationCaseAssignment` (`id` VARCHAR(191) NOT NULL, `caseId` VARCHAR(191) NOT NULL, `moderatorAccountId` VARCHAR(191) NOT NULL, `assignedByAccountId` VARCHAR(191) NOT NULL, `state` VARCHAR(64) NOT NULL DEFAULT 'ASSIGNED', `reasonCode` VARCHAR(191) NOT NULL, `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3), `endedAt` DATETIME(3) NULL, PRIMARY KEY (`id`), KEY `CommunityModerationCaseAssignment_caseId_endedAt_idx` (`caseId`, `endedAt`), KEY `CommunityModerationCaseAssignment_moderatorAccountId_endedAt_idx` (`moderatorAccountId`, `endedAt`)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE TABLE `CommunityModerationCaseEvent` (`id` VARCHAR(191) NOT NULL, `caseId` VARCHAR(191) NOT NULL, `eventType` VARCHAR(64) NOT NULL, `fromStatus` VARCHAR(64) NULL, `toStatus` VARCHAR(64) NULL, `reasonCode` VARCHAR(191) NOT NULL, `actorAccountId` VARCHAR(191) NOT NULL, `correlationId` VARCHAR(191) NOT NULL, `detail` LONGTEXT NOT NULL, `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3), PRIMARY KEY (`id`), KEY `CommunityModerationCaseEvent_caseId_createdAt_idx` (`caseId`, `createdAt`)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE TABLE `CommunityModerationAction` (`id` VARCHAR(191) NOT NULL, `caseId` VARCHAR(191) NOT NULL, `subjectType` VARCHAR(64) NOT NULL, `subjectId` VARCHAR(191) NOT NULL, `actionType` VARCHAR(64) NOT NULL, `state` VARCHAR(64) NOT NULL DEFAULT 'APPLIED', `reasonCode` VARCHAR(191) NOT NULL, `expectedRevision` INT NOT NULL, `idempotencyKey` VARCHAR(191) NOT NULL, `actorAccountId` VARCHAR(191) NOT NULL, `secondReviewerId` VARCHAR(191) NULL, `reversible` BOOLEAN NOT NULL DEFAULT true, `appealEligible` BOOLEAN NOT NULL DEFAULT true, `restorationEligible` BOOLEAN NOT NULL DEFAULT false, `correlationId` VARCHAR(191) NOT NULL, `appliedAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3), `reversedAt` DATETIME(3) NULL, PRIMARY KEY (`id`), UNIQUE KEY `CommunityModerationAction_idempotencyKey_key` (`idempotencyKey`), KEY `CommunityModerationAction_caseId_appliedAt_idx` (`caseId`, `appliedAt`), KEY `CommunityModerationAction_subjectType_subjectId_state_idx` (`subjectType`, `subjectId`, `state`)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE TABLE `CommunitySanction` (`id` VARCHAR(191) NOT NULL, `actionId` VARCHAR(191) NOT NULL, `subjectAccountId` VARCHAR(191) NULL, `sanctionType` VARCHAR(64) NOT NULL, `startsAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3), `endsAt` DATETIME(3) NULL, `state` VARCHAR(64) NOT NULL DEFAULT 'ACTIVE', `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3), PRIMARY KEY (`id`), UNIQUE KEY `CommunitySanction_actionId_key` (`actionId`), KEY `CommunitySanction_subjectAccountId_state_idx` (`subjectAccountId`, `state`)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE TABLE `CommunityModerationAppeal` (`id` VARCHAR(191) NOT NULL, `actionId` VARCHAR(191) NOT NULL, `caseId` VARCHAR(191) NOT NULL, `appellantAccountId` VARCHAR(191) NOT NULL, `status` VARCHAR(64) NOT NULL DEFAULT 'SUBMITTED', `reason` TEXT NOT NULL, `filingDeadlineAt` DATETIME(3) NOT NULL, `assignedAccountId` VARCHAR(191) NULL, `decisionReasonCode` VARCHAR(191) NULL, `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3), `updatedAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3), `closedAt` DATETIME(3) NULL, PRIMARY KEY (`id`), UNIQUE KEY `CommunityModerationAppeal_actionId_appellantAccountId_key` (`actionId`, `appellantAccountId`), KEY `CommunityModerationAppeal_caseId_status_createdAt_idx` (`caseId`, `status`, `createdAt`)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE TABLE `CommunityModerationAppealEvent` (`id` VARCHAR(191) NOT NULL, `appealId` VARCHAR(191) NOT NULL, `eventType` VARCHAR(64) NOT NULL, `fromStatus` VARCHAR(64) NULL, `toStatus` VARCHAR(64) NULL, `reasonCode` VARCHAR(191) NOT NULL, `actorAccountId` VARCHAR(191) NOT NULL, `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3), PRIMARY KEY (`id`), KEY `CommunityModerationAppealEvent_appealId_createdAt_idx` (`appealId`, `createdAt`)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE TABLE `CommunityRestorationReceipt` (`id` VARCHAR(191) NOT NULL, `actionId` VARCHAR(191) NOT NULL, `caseId` VARCHAR(191) NOT NULL, `subjectType` VARCHAR(64) NOT NULL, `subjectId` VARCHAR(191) NOT NULL, `objectChecksum` CHAR(64) NULL, `scanReceiptId` VARCHAR(191) NULL, `packageChecksum` CHAR(64) NULL, `eligibility` LONGTEXT NOT NULL, `restoredBy` VARCHAR(191) NOT NULL, `correlationId` VARCHAR(191) NOT NULL, `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3), PRIMARY KEY (`id`), UNIQUE KEY `CommunityRestorationReceipt_actionId_key` (`actionId`), KEY `CommunityRestorationReceipt_caseId_createdAt_idx` (`caseId`, `createdAt`)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE TABLE `CommunityScanReceipt` (`id` VARCHAR(191) NOT NULL, `subjectType` VARCHAR(64) NOT NULL, `subjectId` VARCHAR(191) NOT NULL, `provider` VARCHAR(191) NOT NULL, `providerVersion` VARCHAR(191) NOT NULL, `definitionsVersion` VARCHAR(191) NULL, `result` VARCHAR(64) NOT NULL, `objectChecksum` CHAR(64) NOT NULL, `byteLength` INT NOT NULL, `detectedMediaType` VARCHAR(191) NOT NULL, `evidenceKind` VARCHAR(191) NOT NULL, `correlationId` VARCHAR(191) NOT NULL, `expiresAt` DATETIME(3) NOT NULL, `scannedAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3), PRIMARY KEY (`id`), KEY `CommunityScanReceipt_subjectType_subjectId_scannedAt_idx` (`subjectType`, `subjectId`, `scannedAt`), KEY `CommunityScanReceipt_objectChecksum_result_expiresAt_idx` (`objectChecksum`, `result`, `expiresAt`)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE TABLE `CommunityRateLimitBucket` (`id` VARCHAR(191) NOT NULL, `keyHash` CHAR(64) NOT NULL, `scope` VARCHAR(191) NOT NULL, `count` INT NOT NULL DEFAULT 0, `windowEndsAt` DATETIME(3) NOT NULL, `updatedAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3), PRIMARY KEY (`id`), UNIQUE KEY `CommunityRateLimitBucket_keyHash_key` (`keyHash`), KEY `CommunityRateLimitBucket_scope_windowEndsAt_idx` (`scope`, `windowEndsAt`)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE TABLE `CommunityOperationalSchedule` (`id` VARCHAR(191) NOT NULL, `scheduleType` VARCHAR(191) NOT NULL, `nextRunAt` DATETIME(3) NOT NULL, `lastRunAt` DATETIME(3) NULL, `lastOutcome` VARCHAR(191) NULL, `revision` INT NOT NULL DEFAULT 1, `updatedAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3), PRIMARY KEY (`id`), UNIQUE KEY `CommunityOperationalSchedule_scheduleType_key` (`scheduleType`), KEY `CommunityOperationalSchedule_nextRunAt_idx` (`nextRunAt`)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
