import { validateLandfallDefinition } from "@/landfall/definition";
import type { LandfallObservation } from "@/landfall/observation";
import type { LandfallCoordinate } from "@/landfall/schema";

export const physicalCoordinate = (latitude: number, longitude: number): LandfallCoordinate => ({
  type: "WGS84",
  worldspaceId: "town",
  referenceId: "town-wgs84",
  referenceVersion: 1,
  latitude,
  longitude,
});
export const virtualCoordinate = (x: number, y: number): LandfallCoordinate => ({
  type: "NORMALIZED_IMAGE_2D",
  worldspaceId: "isles",
  referenceId: "isles-image",
  referenceVersion: 1,
  x,
  y,
});

export const landfallFixture = validateLandfallDefinition({
  schemaVersion: 1,
  taleId: "fixture-tale",
  worldspaces: [
    {
      id: "town",
      name: "Fixture Town",
      kind: "PHYSICAL",
      version: 1,
      coordinateReference: { type: "WGS84", id: "town-wgs84", version: 1, altitude: "IGNORED" },
      mapDefinitionIds: ["town-map"],
      defaultMapDefinitionId: "town-map",
      observationPolicy: { allowedSources: ["BROWSER_GEOLOCATION", "PLAYER_CONFIRMATION"], requiredFallback: true },
      routePolicy: { allowOffRoute: true, maximumRoutePoints: 100 },
      privacyPolicy: {
        classification: "APPROXIMATE_REAL_WORLD",
        retainRawPhysicalSamples: false,
        allowPublicGeometry: false,
      },
      offlinePolicy: "OFFLINE_PARTIAL",
      presentationMetadata: { distanceLabel: "meters" },
    },
    {
      id: "isles",
      name: "Imaginary Isles",
      kind: "VIRTUAL",
      version: 1,
      coordinateReference: {
        type: "NORMALIZED_IMAGE_2D",
        id: "isles-image",
        version: 1,
        bounds: { minX: 0, minY: 0, maxX: 1, maxY: 1 },
        axis: "X_RIGHT_Y_DOWN",
        imageAssetId: "synthetic-chart",
        width: 1000,
        height: 800,
      },
      mapDefinitionIds: ["isles-map"],
      defaultMapDefinitionId: "isles-map",
      observationPolicy: { allowedSources: ["PLAYER_CONFIRMATION", "STORY_PROGRESSION"], requiredFallback: true },
      routePolicy: { allowOffRoute: true, maximumRoutePoints: 100 },
      privacyPolicy: { classification: "FICTIONAL", retainRawPhysicalSamples: false, allowPublicGeometry: true },
      offlinePolicy: "OFFLINE_READY",
      presentationMetadata: { distanceLabel: "map units" },
    },
  ],
  maps: [
    {
      id: "town-map",
      worldspaceId: "town",
      name: "Town Chart",
      role: "PRIMARY",
      referenceId: "town-wgs84",
      renderer: "MAPLIBRE_STYLE",
      source: { type: "BUILTIN_VECTOR", providerId: "fixture-vector", styleId: "fixture-style" },
      attribution: [{ label: "Fixture geography", url: "https://example.invalid/attribution" }],
      camera: { center: physicalCoordinate(44, -72), zoom: 13, bearing: 0, policy: "NORTH_UP" },
      style: { preset: "FIELD_JOURNAL", foreground: "#202020", background: "#f5f5f0" },
      privacyClassification: "APPROXIMATE_REAL_WORLD",
      offlinePolicy: "OFFLINE_PARTIAL",
    },
    {
      id: "isles-map",
      worldspaceId: "isles",
      name: "Isles Chart",
      role: "PRIMARY",
      referenceId: "isles-image",
      renderer: "IMAGE_2D",
      source: { type: "ASSET_IMAGE", assetId: "synthetic-chart" },
      attribution: [],
      camera: { center: virtualCoordinate(0.5, 0.5), zoom: 1, bearing: 0, policy: "USER_CONTROLLED" },
      style: { preset: "PARCHMENT_CHART", foreground: "#332211", background: "#f0dfb0" },
      privacyClassification: "FICTIONAL",
      offlinePolicy: "OFFLINE_READY",
    },
  ],
  waypoints: [
    {
      id: "town-arrival",
      worldspaceId: "town",
      mapId: "town-map",
      name: "Town arrival",
      type: "ARRIVAL_POINT",
      geometry: { type: "POINT_RADIUS", center: physicalCoordinate(44, -72), radius: 100 },
      evidenceProfile: {
        precisionProfile: "BROAD_ARRIVAL",
        acceptedSources: ["BROWSER_GEOLOCATION"],
        requiredAccuracyMeters: 25,
        requiredSamples: 2,
        dwellSeconds: 0,
        enterHysteresis: 0,
        exitHysteresis: 10,
        maximumAgeSeconds: 30,
        maximumSpeedMetersPerSecond: 45,
        minimumCorroboration: 1,
        allowManualFallback: true,
        allowCaptainOverride: true,
      },
      sequence: { afterWaypointIds: [], optional: false },
      visibility: { hiddenUntilRevealed: false, publicLabel: "Town arrival" },
      completion: { requiredOutcome: "CONFIRMED", mode: "OBSERVED" },
      fallback: { mode: "PLAYER" },
      privacyClassification: "APPROXIMATE_REAL_WORLD",
      safety: { daylightOnly: false, weatherSensitive: false, accessibilityLimited: false, captainSupervised: false },
    },
    {
      id: "isle-region",
      worldspaceId: "isles",
      mapId: "isles-map",
      name: "Secret Isle",
      type: "HIDDEN_WAYPOINT",
      geometry: {
        type: "POLYGON",
        rings: [
          [
            virtualCoordinate(0.4, 0.4),
            virtualCoordinate(0.6, 0.4),
            virtualCoordinate(0.6, 0.6),
            virtualCoordinate(0.4, 0.6),
            virtualCoordinate(0.4, 0.4),
          ],
        ],
      },
      evidenceProfile: {
        precisionProfile: "VIRTUAL_CONTEXT",
        acceptedSources: ["PLAYER_CONFIRMATION", "STORY_PROGRESSION"],
        requiredSamples: 1,
        dwellSeconds: 0,
        enterHysteresis: 0,
        exitHysteresis: 0,
        maximumAgeSeconds: 600,
        minimumCorroboration: 1,
        allowManualFallback: true,
        allowCaptainOverride: true,
      },
      sequence: { afterWaypointIds: [], optional: false },
      visibility: { hiddenUntilRevealed: true },
      completion: { requiredOutcome: "CONFIRMED", mode: "OBSERVED" },
      fallback: { mode: "PLAYER" },
      privacyClassification: "FICTIONAL",
      safety: { daylightOnly: false, weatherSensitive: false, accessibilityLimited: false, captainSupervised: false },
    },
  ],
  routes: [
    {
      id: "town-route",
      worldspaceId: "town",
      name: "Town walk",
      model: "GUIDED_CORRIDOR",
      semantics: "NAVIGATIONAL",
      waypointIds: ["town-arrival"],
      geometry: { type: "CORRIDOR", points: [physicalCoordinate(43.999, -72), physicalCoordinate(44, -72)], width: 60 },
      travelMode: "WALKING",
      offRouteTolerance: 50,
      privacyClassification: "APPROXIMATE_REAL_WORLD",
    },
    {
      id: "isle-route",
      worldspaceId: "isles",
      name: "Isle crossing",
      model: "ORDERED",
      semantics: "ILLUSTRATIVE",
      waypointIds: ["isle-region"],
      geometry: { type: "ROUTE_LINE", points: [virtualCoordinate(0.1, 0.1), virtualCoordinate(0.5, 0.5)] },
      travelMode: "BOAT",
      offRouteTolerance: 0.1,
      privacyClassification: "FICTIONAL",
    },
  ],
  transitions: [
    {
      id: "enter-isles",
      fromWorldspaceId: "town",
      toWorldspaceId: "isles",
      trigger: { type: "CHAPTER", id: "chapter-isles" },
      initialLocationId: "isle-region",
      presentation: "STORYTIDE",
      destinationOfflinePolicy: "REQUIRE_READY",
    },
  ],
});

export function physicalObservation(
  id: string,
  observedAt: string,
  latitude = 44,
  longitude = -72,
  accuracyMeters = 8,
): LandfallObservation {
  return {
    schemaVersion: 1,
    id,
    sessionId: "session-1",
    publishedVersionId: "version-1",
    worldspaceId: "town",
    providerId: "sim-physical",
    source: "BROWSER_GEOLOCATION",
    kind: "PHYSICAL_POSITION",
    observedAt,
    coordinate: physicalCoordinate(latitude, longitude),
    accuracyMeters,
  };
}
export function virtualObservation(
  id: string,
  observedAt: string,
  targetLocationId = "isle-region",
  assertion: "PRESENT" | "ABSENT" | "UNCERTAIN" = "PRESENT",
): LandfallObservation {
  return {
    schemaVersion: 1,
    id,
    sessionId: "session-1",
    publishedVersionId: "version-1",
    worldspaceId: "isles",
    providerId: "sim-virtual",
    source: "PLAYER_CONFIRMATION",
    kind: "SEMANTIC_LOCATION",
    observedAt,
    targetLocationId,
    assertion,
    confidence: assertion === "PRESENT" ? 0.99 : 0.4,
  };
}
