import {
  providerDescriptorSchema,
  providerFamilySchema,
  type ProviderDescriptor,
  type ProviderFamily,
  type ProviderStatus,
} from "@/landfall/provider-policy";

type Entry = [string, string, ProviderFamily, string[], Partial<ProviderDescriptor>?];
const physical: ProviderDescriptor["worldspaceKinds"] = ["PHYSICAL"];
const native: ProviderDescriptor["platforms"] = ["IOS", "ANDROID"];
const entries: Entry[] = [
  [
    "maplibre-web",
    "Interactive web chart",
    "MAP_RENDERER",
    ["render", "camera", "layers", "hit-test"],
    { platforms: ["WEB"] },
  ],
  [
    "maplibre-native",
    "Native chart",
    "MAP_RENDERER",
    ["render", "camera", "layers", "offline-render"],
    { platforms: native, worldspaceKinds: physical },
  ],
  [
    "semantic-chart",
    "Written and static chart",
    "MAP_RENDERER",
    ["render", "accessible"],
    { platforms: ["WEB", ...native] },
  ],
  [
    "authored-map",
    "Authored map and floor plan",
    "MAP_DATA",
    ["vector", "raster", "overlay", "floor-plan"],
    { platforms: ["WEB", ...native, "SERVER"], privacy: "FIRST_PARTY" },
  ],
  [
    "osm-standard",
    "OpenStreetMap interactive tiles",
    "MAP_DATA",
    ["raster"],
    {
      worldspaceKinds: physical,
      platforms: ["WEB"],
      network: "REQUIRED",
      offline: false,
      privacy: "THIRD_PARTY",
      attribution: "OpenStreetMap contributors",
      license: "Provider tile usage policy",
      cacheRights: "REQUIRES_AGREEMENT",
      offlineRights: "PROHIBITED",
      maxZoom: 19,
    },
  ],
  [
    "self-hosted-tiles",
    "Configured tile service",
    "MAP_DATA",
    ["vector", "raster", "terrain", "hillshade"],
    {
      network: "REQUIRED",
      offline: false,
      privacy: "THIRD_PARTY",
      license: "Deployment-specific agreement",
      cacheRights: "REQUIRES_AGREEMENT",
      offlineRights: "REQUIRES_AGREEMENT",
    },
  ],
  [
    "packaged-map",
    "Downloaded authorized map region",
    "MAP_DATA",
    ["vector", "raster", "overlay", "floor-plan"],
    { platforms: ["WEB", ...native], privacy: "FIRST_PARTY" },
  ],
  ["authored-places", "Local authored places", "GEOCODING", ["forward", "reverse", "bounded", "proximity", "local"]],
  [
    "configured-geocoder",
    "Configured place search",
    "GEOCODING",
    ["forward", "reverse", "bounded", "proximity"],
    {
      worldspaceKinds: physical,
      platforms: ["SERVER"],
      network: "REQUIRED",
      offline: false,
      requiresCredential: true,
      privacy: "THIRD_PARTY",
      license: "Deployment-specific agreement",
      cacheRights: "REQUIRES_AGREEMENT",
      offlineRights: "REQUIRES_AGREEMENT",
    },
  ],
  ["authored-routes", "Creator routes", "ROUTING", ["authored", "indoor", "virtual", "accessible"]],
  [
    "configured-router",
    "Configured route suggestions",
    "ROUTING",
    ["walking", "cycling", "driving", "suggestion"],
    {
      worldspaceKinds: physical,
      platforms: ["SERVER"],
      network: "REQUIRED",
      offline: false,
      requiresCredential: true,
      privacy: "THIRD_PARTY",
      license: "Deployment-specific agreement",
      cacheRights: "REQUIRES_AGREEMENT",
      offlineRights: "REQUIRES_AGREEMENT",
    },
  ],
  ["authored-elevation", "Authored floor and elevation", "ELEVATION", ["floor", "authored", "virtual"]],
  ["packaged-elevation", "Downloaded terrain", "ELEVATION", ["terrain", "local"], { worldspaceKinds: physical }],
  [
    "configured-elevation",
    "Configured terrain service",
    "ELEVATION",
    ["terrain"],
    {
      worldspaceKinds: physical,
      platforms: ["SERVER"],
      network: "REQUIRED",
      offline: false,
      requiresCredential: true,
      privacy: "THIRD_PARTY",
      license: "Deployment-specific agreement",
      cacheRights: "REQUIRES_AGREEMENT",
      offlineRights: "REQUIRES_AGREEMENT",
    },
  ],
  [
    "browser-geolocation",
    "Foreground browser location",
    "LOCATION",
    ["foreground", "approximate"],
    { worldspaceKinds: physical, platforms: ["WEB"], permissions: ["FOREGROUND_LOCATION"], hardware: "LOCATION" },
  ],
  [
    "ios-core-location",
    "iOS location",
    "LOCATION",
    ["foreground", "background", "significant-change", "approximate"],
    { worldspaceKinds: physical, platforms: ["IOS"], permissions: ["FOREGROUND_LOCATION"], hardware: "LOCATION" },
  ],
  [
    "android-location",
    "Android location",
    "LOCATION",
    ["foreground", "background", "approximate"],
    { worldspaceKinds: physical, platforms: ["ANDROID"], permissions: ["FOREGROUND_LOCATION"], hardware: "LOCATION" },
  ],
  [
    "native-geofence",
    "Broad nearby reminders",
    "GEOFENCE",
    ["wake"],
    {
      worldspaceKinds: physical,
      platforms: native,
      permissions: ["FOREGROUND_LOCATION", "BACKGROUND_LOCATION"],
      hardware: "LOCATION",
    },
  ],
  [
    "device-motion",
    "Movement hints",
    "MOTION",
    ["continuity", "activity"],
    { worldspaceKinds: physical, platforms: ["WEB", ...native], permissions: ["MOTION"], hardware: "MOTION" },
  ],
  [
    "device-heading",
    "Direction hints",
    "HEADING",
    ["heading"],
    { worldspaceKinds: physical, platforms: ["WEB", ...native], hardware: "MOTION" },
  ],
  [
    "device-orientation",
    "Orientation hints",
    "ORIENTATION",
    ["orientation"],
    { worldspaceKinds: physical, platforms: ["WEB", ...native], hardware: "MOTION" },
  ],
  [
    "native-pedestrian",
    "Step and activity hints",
    "PEDESTRIAN",
    ["steps", "activity"],
    { worldspaceKinds: physical, platforms: native, permissions: ["MOTION"], hardware: "MOTION" },
  ],
  [
    "native-barometer",
    "Relative floor movement hints",
    "BAROMETER",
    ["relative-height"],
    { worldspaceKinds: physical, platforms: native, hardware: "BAROMETER" },
  ],
  [
    "native-uwb",
    "Optional short-range ranging",
    "UWB",
    ["ranging"],
    { worldspaceKinds: physical, platforms: native, hardware: "UWB", permissions: ["NEARBY_DEVICES"] },
  ],
  [
    "native-ble",
    "Optional beacon proximity",
    "BLE",
    ["ibeacon", "eddystone", "proximity"],
    { worldspaceKinds: physical, platforms: native, hardware: "BLE", permissions: ["BLUETOOTH", "NEARBY_DEVICES"] },
  ],
  [
    "native-nfc",
    "Optional deliberate tag scan",
    "NFC",
    ["signed-token"],
    { worldspaceKinds: physical, platforms: native, hardware: "NFC", permissions: ["NFC"] },
  ],
  [
    "camera-qr",
    "Optional deliberate code scan",
    "QR",
    ["signed-token", "qr"],
    { platforms: ["WEB", ...native], hardware: "CAMERA", permissions: ["CAMERA"] },
  ],
  [
    "watchglass",
    "Watchglass evidence handoff",
    "VISION",
    ["certified-evidence"],
    { privacy: "FIRST_PARTY", network: "REQUIRED", offline: false },
  ],
  [
    "authored-landmark",
    "Authored landmark comparison",
    "VISION",
    ["authored-comparison"],
    {
      worldspaceKinds: physical,
      platforms: ["WEB"],
      hardware: "CAMERA",
      permissions: ["CAMERA"],
      privacy: "FIRST_PARTY",
      network: "REQUIRED",
      offline: false,
    },
  ],
  ["player-confirmation", "Deliberate Player observation", "PLAYER", ["confirmation"], { privacy: "FIRST_PARTY" }],
  [
    "captain-confirmation",
    "Authorized Captain commands",
    "CAPTAIN",
    ["confirm", "skip", "replace", "reconcile"],
    { privacy: "FIRST_PARTY", network: "REQUIRED", offline: false },
  ],
  [
    "virtual-manual",
    "Authored virtual position",
    "VIRTUAL_POSITION",
    ["authored", "manual"],
    { worldspaceKinds: ["VIRTUAL"] },
  ],
  [
    "game-integration",
    "Configured game integration",
    "GAME_STATE",
    ["game-state"],
    { worldspaceKinds: ["VIRTUAL"], requiresCredential: true },
  ],
  ["virtual-regions", "Authored virtual regions", "VIRTUAL_REGION", ["authored"], { worldspaceKinds: ["VIRTUAL"] }],
  [
    "virtual-events",
    "Configured virtual events",
    "VIRTUAL_EVENT",
    ["game-event"],
    { worldspaceKinds: ["VIRTUAL"], requiresCredential: true },
  ],
  [
    "connectivity",
    "Bounded first-party reachability",
    "CONNECTIVITY",
    ["reachability"],
    { platforms: ["WEB", ...native], network: "OPTIONAL", privacy: "FIRST_PARTY" },
  ],
  [
    "native-local-notifications",
    "Private nearby reminder",
    "NOTIFICATION",
    ["local", "return"],
    { platforms: native, permissions: ["NOTIFICATIONS"] },
  ],
  [
    "web-notifications",
    "Private web reminder",
    "NOTIFICATION",
    ["local", "return"],
    { platforms: ["WEB"], permissions: ["NOTIFICATIONS"] },
  ],
  [
    "offline-regions",
    "Authorized offline journey",
    "OFFLINE_PACKAGE",
    ["download", "integrity", "retention"],
    { platforms: ["WEB", ...native], privacy: "FIRST_PARTY" },
  ],
];

const descriptor = ([providerId, label, family, capabilities, overrides]: Entry): ProviderDescriptor =>
  providerDescriptorSchema.parse({
    id: providerId,
    label,
    family,
    capabilities,
    worldspaceKinds: ["PHYSICAL", "VIRTUAL"],
    platforms: ["WEB", "IOS", "ANDROID", "SERVER"],
    permissions: [],
    network: "NONE",
    hardware: "NONE",
    requiresCredential: false,
    privacy: "LOCAL",
    offline: true,
    simulation: false,
    attribution: "",
    license: "Application-authored content",
    cacheRights: "ALLOWED",
    offlineRights: "ALLOWED",
    ...overrides,
  });

/** Presence in this catalog declares a contract, never installation, hardware availability or success. */
export function landfallProviderCatalog(): ProviderDescriptor[] {
  return entries.map(descriptor);
}
export function landfallSimulationCatalog(): ProviderDescriptor[] {
  return providerFamilySchema.options.map((family) =>
    descriptor([
      `synthetic-${family.toLowerCase().replaceAll("_", "-")}`,
      `Test ${family.toLowerCase().replaceAll("_", " ")}`,
      family,
      ["simulation"],
      { platforms: ["TEST"], simulation: true },
    ]),
  );
}
/** Startup is pessimistic. A runtime adapter must configure and probe itself explicitly. */
export function unconfiguredLandfallStatuses(providers = landfallProviderCatalog()): ProviderStatus[] {
  return providers.map(({ id }) => ({
    id,
    health: "NOT_CONFIGURED",
    configured: false,
    credentialAvailable: false,
    enabled: true,
  }));
}
