CREATE TABLE `DrydockRuleWaiver` (
    `id` VARCHAR(191) NOT NULL,
    `draftId` VARCHAR(191) NOT NULL,
    `issueId` VARCHAR(191) NOT NULL,
    `ruleCode` VARCHAR(191) NOT NULL,
    `ruleVersion` INTEGER NOT NULL,
    `sourceChecksum` VARCHAR(191) NOT NULL,
    `sourceRevision` INTEGER NOT NULL,
    `rationale` TEXT NOT NULL,
    `scope` VARCHAR(191) NOT NULL,
    `authorizedByAccountId` VARCHAR(191) NOT NULL,
    `authorizedRole` VARCHAR(191) NOT NULL,
    `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `expiresAt` DATETIME(3) NULL,
    `reviewCondition` TEXT NULL,
    `carryForwardPolicy` VARCHAR(191) NOT NULL DEFAULT 'DO_NOT_CARRY',
    `revokedAt` DATETIME(3) NULL,
    `auditReference` VARCHAR(191) NULL,
    INDEX `DrydockRuleWaiver_draftId_createdAt_idx` (`draftId`, `createdAt`),
    INDEX `DrydockRuleWaiver_issueId_sourceChecksum_idx` (`issueId`, `sourceChecksum`),
    INDEX `DrydockRuleWaiver_authorizedByAccountId_createdAt_idx` (`authorizedByAccountId`, `createdAt`),
    PRIMARY KEY (`id`),
    CONSTRAINT `DrydockRuleWaiver_draftId_fkey` FOREIGN KEY (`draftId`) REFERENCES `TaleDraft` (`id`) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT `DrydockRuleWaiver_authorizedByAccountId_fkey` FOREIGN KEY (`authorizedByAccountId`) REFERENCES `UserAccount` (`id`) ON DELETE RESTRICT ON UPDATE CASCADE
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
