import { cp, mkdir, rm } from "node:fs/promises";
import path from "node:path";
const root = process.cwd();
const standalone = path.join(root, ".next", "standalone");
const target = path.join(root, ".desktop-bundle", "app-server");
await rm(target, { recursive: true, force: true });
await mkdir(target, { recursive: true });
await cp(standalone, target, { recursive: true, dereference: true });
await mkdir(path.join(target, ".next"), { recursive: true });
await cp(path.join(root, ".next", "static"), path.join(target, ".next", "static"), { recursive: true });
await cp(path.join(root, "public"), path.join(target, "public"), { recursive: true });
console.log(JSON.stringify({ staged: true, target, source: standalone }));
