import { canonicalTerms } from "@/language/canonical-terms";
import { platformCopy } from "@/language/platform-copy";
import type { NavigationItem, ShellMode, WorkspaceDefinition, WorkspaceId } from "./types";

const ordinaryModes = [
  "GATEWAY_STANDARD",
  "PUBLIC_STANDARD",
  "WORKSPACE_STANDARD",
] as const satisfies readonly ShellMode[];
const workspaceModes = ["WORKSPACE_STANDARD"] as const satisfies readonly ShellMode[];
const accountModes = [
  "GATEWAY_STANDARD",
  "PUBLIC_STANDARD",
  "WORKSPACE_STANDARD",
  "COMPACT",
  "IMMERSIVE",
] as const satisfies readonly ShellMode[];

export const workspaceRegistry: Readonly<Record<WorkspaceId, WorkspaceDefinition>> = {
  public: { id: "public", label: canonicalTerms.product, homeHref: "/" },
  player: { id: "player", label: canonicalTerms.player, homeHref: "/player/library" },
  captain: { id: "captain", label: canonicalTerms.captainConsole, homeHref: "/captain/library" },
  creator: { id: "creator", label: canonicalTerms.studio, homeHref: "/studio/library" },
  account: { id: "account", label: "Personal Harbor", homeHref: "/account" },
  community: { id: "community", label: "Community Harbor", homeHref: "/community" },
  development: { id: "development", label: "Development", homeHref: "/dev/animations" },
};

const globalItems = [
  {
    id: "global-home",
    layer: "GLOBAL",
    label: "Home",
    href: "/",
    owner: "true-north",
    shellModes: ordinaryModes,
    desktop: "primary",
    mobile: "drawer",
    activeMatch: { type: "EXACT" },
    order: 10,
    currentStatus: "active",
  },
  {
    id: "global-explore-chronicles",
    layer: "GLOBAL",
    label: platformCopy.exploreChronicles.value,
    href: "/tales",
    owner: "true-north",
    shellModes: ordinaryModes,
    desktop: "primary",
    mobile: "drawer",
    activeMatch: { type: "SECTION" },
    order: 20,
    currentStatus: "active",
  },
  {
    id: "global-community-harbor",
    layer: "GLOBAL",
    label: "Community Harbor",
    href: "/community",
    owner: "harborlight",
    shellModes: ordinaryModes,
    desktop: "primary",
    mobile: "drawer",
    activeMatch: { type: "SECTION" },
    order: 30,
    currentStatus: "active",
  },
] as const satisfies readonly NavigationItem[];

const workspaceItems = [
  {
    id: "workspace-player-home",
    layer: "WORKSPACE",
    label: "My Voyages",
    href: "/player/library",
    owner: "one-voyage",
    requiredCapabilities: ["player"],
    requiresAuthentication: true,
    shellModes: workspaceModes,
    desktop: "primary",
    mobile: "drawer",
    activeMatch: { type: "SECTION" },
    order: 10,
    currentStatus: "active",
  },
  {
    id: "workspace-captain-voyages",
    layer: "WORKSPACE",
    label: "Voyages",
    href: "/captain/library",
    owner: "one-voyage",
    requiredCapabilities: ["captain"],
    requiresAuthentication: true,
    shellModes: workspaceModes,
    desktop: "primary",
    mobile: "drawer",
    activeMatch: { type: "SECTION" },
    order: 10,
    currentStatus: "active",
  },
  {
    id: "workspace-captain-invitations",
    layer: "WORKSPACE",
    label: "Crew invitations",
    shortLabel: "Invitations",
    href: "/captain/library?tab=invitations",
    owner: "one-voyage",
    requiredCapabilities: ["captain"],
    requiresAuthentication: true,
    shellModes: workspaceModes,
    desktop: "primary",
    mobile: "drawer",
    activeMatch: { type: "NEVER_ACTIVE" },
    order: 20,
    currentStatus: "active",
  },
  {
    id: "workspace-creator-library",
    layer: "WORKSPACE",
    label: canonicalTerms.chronicleLibrary,
    href: "/studio/library",
    owner: "one-voyage",
    requiredCapabilities: ["creator"],
    requiresAuthentication: true,
    shellModes: workspaceModes,
    desktop: "primary",
    mobile: "drawer",
    activeMatch: { type: "SECTION" },
    order: 10,
    currentStatus: "active",
  },
  {
    id: "workspace-creator-exchange",
    layer: "WORKSPACE",
    label: "Exchange",
    href: "/studio/exchange",
    owner: "one-voyage",
    requiredCapabilities: ["creator"],
    requiresAuthentication: true,
    shellModes: workspaceModes,
    desktop: "primary",
    mobile: "drawer",
    activeMatch: { type: "SECTION" },
    order: 20,
    currentStatus: "active",
  },
  {
    id: "workspace-creator-private-content",
    layer: "WORKSPACE",
    label: "Private Chronicle",
    href: "/studio/private-content",
    owner: "sealed-hold",
    requiredCapabilities: ["creator"],
    requiresAuthentication: true,
    shellModes: workspaceModes,
    desktop: "primary",
    mobile: "drawer",
    activeMatch: { type: "SECTION" },
    order: 30,
    currentStatus: "active",
  },
] as const satisfies readonly NavigationItem[];

const accountItems = [
  {
    id: "account-create",
    layer: "ACCOUNT",
    label: "Create Account",
    href: "/register",
    owner: "wayfarer",
    anonymousOnly: true,
    shellModes: accountModes,
    desktop: "account",
    mobile: "account",
    activeMatch: { type: "NEVER_ACTIVE" },
    accountGroup: "identity",
    order: 10,
    currentStatus: "active",
  },
  {
    id: "account-sign-in",
    layer: "ACCOUNT",
    label: "Sign In",
    href: ({ pathname }) => `/sign-in?returnTo=${encodeURIComponent(pathname)}`,
    owner: "wayfarer",
    anonymousOnly: true,
    shellModes: accountModes,
    desktop: "account",
    mobile: "account",
    activeMatch: { type: "NEVER_ACTIVE" },
    accountGroup: "identity",
    order: 20,
    currentStatus: "active",
  },
  {
    id: "account-forgot-password",
    layer: "ACCOUNT",
    label: "Forgot Password",
    href: "/forgot-password",
    owner: "wayfarer",
    anonymousOnly: true,
    shellModes: accountModes,
    desktop: "account",
    mobile: "account",
    activeMatch: { type: "NEVER_ACTIVE" },
    accountGroup: "identity",
    order: 30,
    currentStatus: "active",
  },
  {
    id: "account-personal-harbor",
    layer: "ACCOUNT",
    label: "Personal Harbor",
    href: "/account",
    owner: "project-homeport",
    requiresAuthentication: true,
    authenticatedOnly: true,
    shellModes: accountModes,
    desktop: "account",
    mobile: "account",
    activeMatch: { type: "EXACT" },
    accountGroup: "personal",
    order: 5,
    currentStatus: "active",
  },
  {
    id: "account-view-profile",
    layer: "ACCOUNT",
    label: "View My Profile",
    href: "/account/profile/view",
    owner: "project-homeport",
    requiresAuthentication: true,
    authenticatedOnly: true,
    shellModes: accountModes,
    desktop: "account",
    mobile: "account",
    activeMatch: { type: "EXACT" },
    accountGroup: "identity",
    order: 10,
    currentStatus: "active",
  },
  {
    id: "account-passport",
    layer: "ACCOUNT",
    label: "Chronicle Passport",
    href: "/passport",
    owner: "wayfarer",
    requiresAuthentication: true,
    authenticatedOnly: true,
    shellModes: accountModes,
    desktop: "account",
    mobile: "account",
    activeMatch: { type: "EXACT" },
    accountGroup: "personal",
    order: 20,
    currentStatus: "active",
  },
  {
    id: "account-preferences",
    layer: "ACCOUNT",
    label: "Preferences",
    href: "/account/preferences",
    owner: "wayfarer",
    requiresAuthentication: true,
    authenticatedOnly: true,
    shellModes: accountModes,
    desktop: "account",
    mobile: "account",
    activeMatch: { type: "EXACT" },
    parentId: "account-personal-harbor",
    accountGroup: "personal",
    order: 30,
    currentStatus: "active",
  },
  {
    id: "account-privacy",
    layer: "ACCOUNT",
    label: "Privacy & Safety",
    href: "/account/privacy",
    owner: "wayfarer",
    requiresAuthentication: true,
    authenticatedOnly: true,
    shellModes: accountModes,
    desktop: "account",
    mobile: "account",
    activeMatch: { type: "EXACT" },
    parentId: "account-personal-harbor",
    accountGroup: "personal",
    order: 40,
    currentStatus: "active",
  },
  {
    id: "account-history",
    layer: "ACCOUNT",
    label: "Chronicle History",
    href: "/passport/history",
    owner: "wayfarer",
    requiresAuthentication: true,
    authenticatedOnly: true,
    shellModes: accountModes,
    desktop: "account",
    mobile: "account",
    activeMatch: { type: "SECTION" },
    parentId: "account-passport",
    accountGroup: "personal",
    order: 50,
    currentStatus: "active",
  },
  {
    id: "account-artifacts",
    layer: "ACCOUNT",
    label: "Artifact Cabinet",
    href: "/passport/artifacts",
    owner: "wayfarer",
    requiresAuthentication: true,
    authenticatedOnly: true,
    shellModes: accountModes,
    desktop: "account",
    mobile: "account",
    activeMatch: { type: "SECTION" },
    parentId: "account-passport",
    accountGroup: "personal",
    order: 60,
    currentStatus: "active",
  },
  {
    id: "account-security-sessions",
    layer: "ACCOUNT",
    label: "Security & Sessions",
    href: "/account/security",
    owner: "wayfarer",
    requiresAuthentication: true,
    authenticatedOnly: true,
    shellModes: accountModes,
    desktop: "account",
    mobile: "account",
    activeMatch: { type: "SECTION" },
    accountGroup: "personal",
    order: 70,
    currentStatus: "active",
  },
  {
    id: "account-sessions",
    layer: "ACCOUNT",
    label: "Sessions & Devices",
    href: "/account/sessions",
    owner: "wayfarer",
    requiresAuthentication: true,
    authenticatedOnly: true,
    shellModes: accountModes,
    desktop: "account",
    mobile: "account",
    activeMatch: { type: "EXACT" },
    accountGroup: "personal",
    order: 80,
    currentStatus: "active",
  },
  {
    id: "account-support-access",
    layer: "ACCOUNT",
    label: "Support Access",
    href: "/account/support-access",
    owner: "admiralty",
    requiresAuthentication: true,
    authenticatedOnly: true,
    shellModes: accountModes,
    desktop: "account",
    mobile: "account",
    activeMatch: { type: "EXACT" },
    accountGroup: "personal",
    order: 90,
    currentStatus: "active",
  },
  {
    id: "account-all-workspaces",
    layer: "ACCOUNT",
    label: "All Workspaces",
    href: "/account/roles",
    owner: "one-voyage",
    requiresAuthentication: true,
    authenticatedOnly: true,
    shellModes: accountModes,
    desktop: "account",
    mobile: "account",
    activeMatch: { type: "EXACT" },
    accountGroup: "workspace",
    order: 5,
    currentStatus: "active",
  },
  {
    id: "account-workspace-player",
    layer: "ACCOUNT",
    label: "Player",
    href: "/player/library",
    owner: "one-voyage",
    requiredCapabilities: ["player"],
    requiresAuthentication: true,
    authenticatedOnly: true,
    shellModes: accountModes,
    desktop: "account",
    mobile: "account",
    activeMatch: { type: "SECTION" },
    accountGroup: "workspace",
    order: 10,
    currentStatus: "active",
  },
  {
    id: "account-workspace-captain",
    layer: "ACCOUNT",
    label: "Captain",
    href: "/captain/library",
    owner: "one-voyage",
    requiredCapabilities: ["captain"],
    requiresAuthentication: true,
    authenticatedOnly: true,
    shellModes: accountModes,
    desktop: "account",
    mobile: "account",
    activeMatch: { type: "SECTION" },
    accountGroup: "workspace",
    order: 20,
    currentStatus: "active",
  },
  {
    id: "account-workspace-creator",
    layer: "ACCOUNT",
    label: "Creator Studio",
    href: "/studio/library",
    owner: "one-voyage",
    requiredCapabilities: ["creator"],
    requiresAuthentication: true,
    authenticatedOnly: true,
    shellModes: accountModes,
    desktop: "account",
    mobile: "account",
    activeMatch: { type: "SECTION" },
    accountGroup: "workspace",
    order: 30,
    currentStatus: "active",
  },
  {
    id: "account-workspace-moderator",
    layer: "ACCOUNT",
    label: "Moderation",
    href: "/community/moderation",
    owner: "harborlight",
    requiredCapabilities: ["moderator"],
    requiresAuthentication: true,
    authenticatedOnly: true,
    shellModes: accountModes,
    desktop: "account",
    mobile: "account",
    activeMatch: { type: "SECTION" },
    accountGroup: "workspace",
    order: 40,
    currentStatus: "active",
  },
  {
    id: "account-sign-out",
    layer: "ACCOUNT",
    label: "Sign Out",
    href: null,
    action: "sign-out",
    owner: "wayfarer",
    requiresAuthentication: true,
    authenticatedOnly: true,
    shellModes: accountModes,
    desktop: "account",
    mobile: "account",
    activeMatch: { type: "NEVER_ACTIVE" },
    accountGroup: "action",
    order: 10,
    currentStatus: "active",
  },
] as const satisfies readonly NavigationItem[];

const contextualItems = [
  {
    id: "context-chronicles-parent",
    layer: "CONTEXTUAL",
    label: "Back to Explore Chronicles",
    href: "/tales",
    owner: "one-voyage",
    shellModes: ["PUBLIC_STANDARD"],
    desktop: "contextual",
    mobile: "contextual",
    activeMatch: { type: "NEVER_ACTIVE" },
    contextPatterns: ["/play/:slug", "/play/:slug/history", "/tale/:slug"],
    order: 10,
    currentStatus: "contextual",
  },
  {
    id: "context-personal-parent",
    layer: "CONTEXTUAL",
    label: "Personal Harbor",
    href: "/account",
    owner: "wayfarer",
    shellModes: ["PUBLIC_STANDARD", "WORKSPACE_STANDARD"],
    desktop: "contextual",
    mobile: "contextual",
    activeMatch: { type: "NEVER_ACTIVE" },
    contextPatterns: ["/profile/:handle"],
    order: 10,
    currentStatus: "contextual",
  },
  {
    id: "context-captain-exit",
    layer: "CONTEXTUAL",
    label: "Exit to Captain Voyages",
    href: "/captain/library",
    owner: "one-voyage",
    requiredCapabilities: ["captain"],
    requiresAuthentication: true,
    shellModes: ["COMPACT"],
    desktop: "contextual",
    mobile: "contextual",
    activeMatch: { type: "NEVER_ACTIVE" },
    contextPatterns: ["/quartermaster", "/quartermaster/:workspace", "/captain/sessions/:id"],
    order: 10,
    currentStatus: "contextual",
  },
  {
    id: "context-player-exit",
    layer: "CONTEXTUAL",
    label: "Exit to My Voyages",
    href: "/player/library",
    owner: "one-voyage",
    requiredCapabilities: ["player"],
    requiresAuthentication: true,
    shellModes: ["IMMERSIVE"],
    desktop: "contextual",
    mobile: "contextual",
    activeMatch: { type: "NEVER_ACTIVE" },
    contextPatterns: ["/player/playthroughs/:id", "/player/playthroughs/:id/journal", "/play/:slug/session/:id"],
    order: 10,
    currentStatus: "contextual",
  },
  {
    id: "context-development-exit",
    layer: "CONTEXTUAL",
    label: "Exit development tools",
    href: "/",
    owner: "project-homeport",
    shellModes: ["DEVELOPMENT"],
    desktop: "contextual",
    mobile: "contextual",
    activeMatch: { type: "NEVER_ACTIVE" },
    contextPatterns: ["/dev/*"],
    order: 10,
    currentStatus: "development",
  },
] as const satisfies readonly NavigationItem[];

const compatibilityAliases = [
  {
    id: "alias-player-root",
    layer: "WORKSPACE",
    label: "Player compatibility entry",
    href: "/player",
    owner: "one-voyage",
    shellModes: workspaceModes,
    desktop: "hidden",
    mobile: "hidden",
    activeMatch: { type: "ALIAS_OF", canonicalItemId: "workspace-player-home", pattern: "/player" },
    order: 900,
    currentStatus: "compatibility",
  },
  {
    id: "alias-captain-root",
    layer: "WORKSPACE",
    label: "Captain compatibility entry",
    href: "/captain",
    owner: "one-voyage",
    shellModes: workspaceModes,
    desktop: "hidden",
    mobile: "hidden",
    activeMatch: { type: "ALIAS_OF", canonicalItemId: "workspace-captain-voyages", pattern: "/captain" },
    order: 910,
    currentStatus: "compatibility",
  },
  {
    id: "alias-creator-root",
    layer: "WORKSPACE",
    label: "Creator compatibility entry",
    href: "/studio",
    owner: "one-voyage",
    shellModes: workspaceModes,
    desktop: "hidden",
    mobile: "hidden",
    activeMatch: { type: "ALIAS_OF", canonicalItemId: "workspace-creator-library", pattern: "/studio" },
    order: 920,
    currentStatus: "compatibility",
  },
] as const satisfies readonly NavigationItem[];

export const navigationRegistry = [
  ...globalItems,
  ...workspaceItems,
  ...accountItems,
  ...contextualItems,
  ...compatibilityAliases,
] as const satisfies readonly NavigationItem[];

export const allNavigationItems: readonly NavigationItem[] = navigationRegistry;
