import type { RouteShellDefinition, ShellMode, WorkspaceId } from "./types";
import { routePatternMatches } from "./route-matching";

export const routeShellDefinitions: readonly RouteShellDefinition[] = [
  {
    id: "gateway",
    pattern: "/",
    workspace: "public",
    shellMode: "GATEWAY_STANDARD",
    owner: "true-north",
    reason: "Primary cinematic arrival with persistent global and account access.",
    activeFamily: "global-home",
  },
  {
    id: "token-account-claim",
    pattern: "/account/claim",
    workspace: "account",
    shellMode: "TOKENIZED",
    owner: "wayfarer",
    reason: "Bounded account-claim handoff.",
    exitTarget: "/sign-in",
  },
  {
    id: "token-account-merge",
    pattern: "/account/merge",
    workspace: "account",
    shellMode: "TOKENIZED",
    owner: "wayfarer",
    reason: "Bounded account-merge handoff.",
    exitTarget: "/passport",
  },
  ...["/account/email-change", "/account/reactivate", "/account/cancel-deletion"].map(
    (pattern, index) =>
      ({
        id: `token-account-recovery-${index + 1}`,
        pattern,
        workspace: "account",
        shellMode: "TOKENIZED",
        owner: "wayfarer",
        reason: "Bounded verified account lifecycle recovery handoff.",
        exitTarget: "/sign-in",
      }) satisfies RouteShellDefinition,
  ),
  {
    id: "account-root",
    pattern: "/account",
    workspace: "account",
    shellMode: "WORKSPACE_STANDARD",
    owner: "project-homeport",
    reason: "Canonical Personal Harbor overview.",
    exitTarget: "/",
    activeFamily: "account-personal-harbor",
  },
  {
    id: "account",
    pattern: "/account/*",
    workspace: "account",
    shellMode: "WORKSPACE_STANDARD",
    owner: "wayfarer",
    reason: "Ordinary account and security surface.",
    exitTarget: "/account",
    activeFamily: "account-personal-harbor",
  },
  {
    id: "passport",
    pattern: "/passport",
    workspace: "account",
    shellMode: "WORKSPACE_STANDARD",
    owner: "wayfarer",
    reason: "Ordinary Personal Harbor surface.",
    activeFamily: "account-passport",
  },
  {
    id: "passport-family",
    pattern: "/passport/*",
    workspace: "account",
    shellMode: "WORKSPACE_STANDARD",
    owner: "wayfarer",
    reason: "Chronicle Passport record family within Personal Harbor.",
    exitTarget: "/passport",
    activeFamily: "account-passport",
  },
  {
    id: "profile",
    pattern: "/profile/:handle",
    workspace: "account",
    shellMode: "PUBLIC_STANDARD",
    owner: "wayfarer",
    reason: "Public Profile projection.",
    exitTarget: "/account",
    activeFamily: "account-view-profile",
  },
  ...["/sign-in", "/register", "/forgot-password", "/player/sign-in", "/captain/sign-in", "/studio/sign-in"].map(
    (pattern, index) =>
      ({
        id: `authentication-${index + 1}`,
        pattern,
        workspace: pattern.startsWith("/player/")
          ? "player"
          : pattern.startsWith("/captain/")
            ? "captain"
            : pattern.startsWith("/studio/")
              ? "creator"
              : "public",
        shellMode: "AUTHENTICATION",
        owner: "wayfarer",
        reason: "Canonical account lifecycle or bounded role-intent adapter.",
        exitTarget: "/",
      }) satisfies RouteShellDefinition,
  ),
  ...["/reset-password", "/verify-email", "/player/invitation"].map(
    (pattern, index) =>
      ({
        id: `tokenized-${index + 1}`,
        pattern,
        workspace: pattern.startsWith("/player/") ? "player" : "account",
        shellMode: "TOKENIZED",
        owner: "wayfarer",
        reason: "Tokenized lifecycle or invitation handoff with bounded safe return.",
        exitTarget: "/sign-in",
      }) satisfies RouteShellDefinition,
  ),
  {
    id: "immersive-player-journal",
    pattern: "/player/playthroughs/:id/journal",
    workspace: "player",
    shellMode: "IMMERSIVE",
    owner: "one-voyage",
    reason: "Canonical PageFlip Chronicle experience.",
    exitTarget: "/player/library",
    activeFamily: "workspace-player-home",
  },
  {
    id: "immersive-player-archive",
    pattern: "/player/playthroughs/:id/archive",
    workspace: "player",
    shellMode: "IMMERSIVE",
    owner: "one-voyage",
    reason: "Compatibility redirect into the canonical historical journal.",
    exitTarget: "/player/library",
    activeFamily: "workspace-player-home",
  },
  {
    id: "immersive-player-voyage",
    pattern: "/player/playthroughs/:id",
    workspace: "player",
    shellMode: "IMMERSIVE",
    owner: "one-voyage",
    reason: "Invitation/lobby/active Voyage handoff using reduced Player framing.",
    exitTarget: "/player/library",
    activeFamily: "workspace-player-home",
  },
  {
    id: "immersive-player-session",
    pattern: "/play/:slug/session/:id",
    workspace: "player",
    shellMode: "IMMERSIVE",
    owner: "one-voyage",
    reason: "Legacy entry into the canonical PageFlip Chronicle experience.",
    exitTarget: "/player/library",
    activeFamily: "workspace-player-home",
  },
  {
    id: "compact-quartermaster-root",
    pattern: "/quartermaster",
    workspace: "captain",
    shellMode: "COMPACT",
    owner: "one-voyage",
    reason: "Compatibility-focused Captain operational route.",
    canonicalRoute: "/captain/library",
    exitTarget: "/captain/library",
    activeFamily: "workspace-captain-voyages",
  },
  {
    id: "compact-quartermaster",
    pattern: "/quartermaster/:workspace",
    workspace: "captain",
    shellMode: "COMPACT",
    owner: "one-voyage",
    reason: "Focused Captain operational tool.",
    canonicalRoute: "/captain/library",
    exitTarget: "/captain/library",
    activeFamily: "workspace-captain-voyages",
  },
  {
    id: "compact-captain-session",
    pattern: "/captain/sessions/:id",
    workspace: "captain",
    shellMode: "COMPACT",
    owner: "one-voyage",
    reason: "Focused Captain live-session controls.",
    exitTarget: "/captain/library",
    activeFamily: "workspace-captain-voyages",
  },
  {
    id: "community-root",
    pattern: "/community",
    workspace: "community",
    shellMode: "PUBLIC_STANDARD",
    owner: "harborlight",
    reason: "Public Community Harbor root.",
    activeFamily: "global-community-harbor",
  },
  {
    id: "community-family",
    pattern: "/community/*",
    workspace: "community",
    shellMode: "PUBLIC_STANDARD",
    owner: "harborlight",
    reason: "Public or permission-aware Community route family.",
    exitTarget: "/community",
    activeFamily: "global-community-harbor",
  },
  {
    id: "captain-root",
    pattern: "/captain",
    workspace: "captain",
    shellMode: "WORKSPACE_STANDARD",
    owner: "one-voyage",
    reason: "Captain compatibility root.",
    canonicalRoute: "/captain/library",
    activeFamily: "workspace-captain-voyages",
  },
  {
    id: "captain-family",
    pattern: "/captain/*",
    workspace: "captain",
    shellMode: "WORKSPACE_STANDARD",
    owner: "one-voyage",
    reason: "Ordinary Captain workspace family.",
    activeFamily: "workspace-captain-voyages",
  },
  {
    id: "creator-root",
    pattern: "/studio",
    workspace: "creator",
    shellMode: "WORKSPACE_STANDARD",
    owner: "one-voyage",
    reason: "Creator compatibility root.",
    canonicalRoute: "/studio/library",
    activeFamily: "workspace-creator-library",
  },
  {
    id: "creator-family",
    pattern: "/studio/*",
    workspace: "creator",
    shellMode: "WORKSPACE_STANDARD",
    owner: "one-voyage",
    reason: "Ordinary Creator workspace family.",
    activeFamily: "workspace-creator-library",
  },
  {
    id: "player-root",
    pattern: "/player",
    workspace: "player",
    shellMode: "WORKSPACE_STANDARD",
    owner: "one-voyage",
    reason: "Player compatibility root.",
    canonicalRoute: "/player/library",
    activeFamily: "workspace-player-home",
  },
  {
    id: "player-family",
    pattern: "/player/*",
    workspace: "player",
    shellMode: "WORKSPACE_STANDARD",
    owner: "one-voyage",
    reason: "Ordinary Player workspace family.",
    activeFamily: "workspace-player-home",
  },
  {
    id: "public-tales",
    pattern: "/tales",
    workspace: "public",
    shellMode: "PUBLIC_STANDARD",
    owner: "one-voyage",
    reason: "Public Chronicle discovery.",
    activeFamily: "global-explore-chronicles",
  },
  {
    id: "public-play",
    pattern: "/play/:slug",
    workspace: "public",
    shellMode: "PUBLIC_STANDARD",
    owner: "one-voyage",
    reason: "Public Chronicle compatibility route.",
    exitTarget: "/tales",
    activeFamily: "global-explore-chronicles",
  },
  {
    id: "public-play-history",
    pattern: "/play/:slug/history",
    workspace: "public",
    shellMode: "PUBLIC_STANDARD",
    owner: "one-voyage",
    reason: "Public Chronicle history route.",
    exitTarget: "/tales",
    activeFamily: "global-explore-chronicles",
  },
  {
    id: "public-tale-alias",
    pattern: "/tale/:slug",
    workspace: "public",
    shellMode: "PUBLIC_STANDARD",
    owner: "one-voyage",
    reason: "Legacy Chronicle compatibility alias.",
    exitTarget: "/tales",
    activeFamily: "global-explore-chronicles",
  },
  {
    id: "development",
    pattern: "/dev/*",
    workspace: "development",
    shellMode: "DEVELOPMENT",
    owner: "project-homeport",
    reason: "Developer-only diagnostic surface excluded from ordinary navigation.",
    exitTarget: "/",
  },
];

const rank = (definition: RouteShellDefinition) => {
  const literalLength = definition.pattern.replace(/:[^/]+|\*/g, "").length;
  const dynamicPenalty = (definition.pattern.match(/:[^/]+|\*/g) ?? []).length;
  return literalLength * 10 - dynamicPenalty;
};

export function matchingRouteDefinitions(pathname: string) {
  return routeShellDefinitions.filter((definition) => routePatternMatches(pathname, definition.pattern));
}

export function classifyRoute(pathname: string): RouteShellDefinition {
  const matches = matchingRouteDefinitions(pathname);
  return (
    [...matches].sort((left, right) => rank(right) - rank(left))[0] ?? {
      id: "public-default",
      pattern: "*",
      workspace: "public" as WorkspaceId,
      shellMode: "PUBLIC_STANDARD" as ShellMode,
      owner: "true-north",
      reason: "Safe public fallback for an uncataloged ordinary route.",
    }
  );
}
