-- Closure migration: Harborlight foreign keys and durable outbox claims.
ALTER TABLE `CommunityOutboxEvent` ADD COLUMN `claimOwner` VARCHAR(191) NULL, ADD COLUMN `claimExpiresAt` DATETIME(3) NULL, ADD COLUMN `maxAttempts` INTEGER NOT NULL DEFAULT 5;
CREATE INDEX `CommunityOutboxEvent_processedAt_availableAt_claimExpiresAt_idx` ON `CommunityOutboxEvent`(`processedAt`,`availableAt`,`claimExpiresAt`);
ALTER TABLE `CommunityProfile` ADD CONSTRAINT `CommunityProfile_playerProfileId_fkey` FOREIGN KEY (`playerProfileId`) REFERENCES `PlayerProfile`(`id`) ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE `CommunityListing` ADD CONSTRAINT `CommunityListing_ownerProfileId_fkey` FOREIGN KEY (`ownerProfileId`) REFERENCES `CommunityProfile`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE, ADD CONSTRAINT `CommunityListing_currentReleaseId_fkey` FOREIGN KEY (`currentReleaseId`) REFERENCES `CommunityRelease`(`id`) ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE `CommunityRelease` ADD CONSTRAINT `CommunityRelease_listingId_fkey` FOREIGN KEY (`listingId`) REFERENCES `CommunityListing`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE, ADD CONSTRAINT `CommunityRelease_sourcePublishedTaleVersionId_fkey` FOREIGN KEY (`sourcePublishedTaleVersionId`) REFERENCES `PublishedTaleVersion`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE, ADD CONSTRAINT `CommunityRelease_publishedByProfileId_fkey` FOREIGN KEY (`publishedByProfileId`) REFERENCES `CommunityProfile`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE `CommunityReleaseAttribution` ADD CONSTRAINT `CommunityReleaseAttribution_releaseId_fkey` FOREIGN KEY (`releaseId`) REFERENCES `CommunityRelease`(`id`) ON DELETE CASCADE ON UPDATE CASCADE, ADD CONSTRAINT `CommunityReleaseAttribution_creditedProfileId_fkey` FOREIGN KEY (`creditedProfileId`) REFERENCES `CommunityProfile`(`id`) ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE `CommunityOwnershipDeclaration` ADD CONSTRAINT `CommunityOwnershipDeclaration_listingId_fkey` FOREIGN KEY (`listingId`) REFERENCES `CommunityListing`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE, ADD CONSTRAINT `CommunityOwnershipDeclaration_releaseId_fkey` FOREIGN KEY (`releaseId`) REFERENCES `CommunityRelease`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE, ADD CONSTRAINT `CommunityOwnershipDeclaration_declarantProfileId_fkey` FOREIGN KEY (`declarantProfileId`) REFERENCES `CommunityProfile`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE `CommunityAssetReference` ADD CONSTRAINT `CommunityAssetReference_ownerProfileId_fkey` FOREIGN KEY (`ownerProfileId`) REFERENCES `CommunityProfile`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE, ADD CONSTRAINT `CommunityAssetReference_releaseId_fkey` FOREIGN KEY (`releaseId`) REFERENCES `CommunityRelease`(`id`) ON DELETE SET NULL ON UPDATE CASCADE;
